export const SUPPORTED_LANGUAGES: string[];
export const UNIT_GROUPS: Record<string, { base: string; units: Record<string, number>; defaultFrom: string; defaultTo: string }>;
export const TEMP_UNITS: string[];
export const POPULAR_VERSION: number;

export function parseFiniteNumber(value: string | number): number | null;
export function convertUnit(value: string | number, groupId: string | undefined, from: string, to: string): number | null;
export function convertTemperature(value: string | number, from: string, to: string): number | null;
export function formatNumber(value: number, locale?: string): string;
export function formatJson(input: string, mode?: string): { ok: true; value: string } | { ok: false; error: string };
export function base64Encode(input: string): string;
export function base64Decode(input: string): { ok: true; value: string } | { ok: false; error: string };
export function urlTransform(input: string, mode: string): { ok: true; value: string } | { ok: false; error: string };
export function timestampToDate(input: string | number): string | null;
export function dateToTimestamp(input: string, unit?: string): number | null;
export function textStats(input: string): { characters: number; words: number; lines: number };
export function changeCase(input: string, mode: string): string;
export function hexToRgb(hex: string): { r: number; g: number; b: number } | null;
export function rgbToHex(r: string | number, g: string | number, b: string | number): string | null;
export function rgbToHsl(r: string | number, g: string | number, b: string | number): { h: number; s: number; l: number } | null;
export function percentOf(percent: string | number, value: string | number): number | null;
export function discountPrice(price: string | number, discountPercent: string | number): { finalPrice: number; saved: number } | null;
export function bmi(weightKg: string | number, heightCm: string | number): number | null;
export function compoundInterest(principal: string | number, annualRatePercent: string | number, years: string | number, compoundsPerYear?: string | number): { amount: number; interest: number } | null;
export function dateInterval(start: string, end: string): number | null;
export function validateQrInput(value: string): { ok: true } | { ok: false; error: "empty" | "tooLong" };
export function readToolStats(storage?: Storage | null): { version: number; tools: Record<string, { count: number; lastOpenedAt: number }> };
export function trackToolOpen(storage: Storage | null, toolId: string, now?: number): { version: number; tools: Record<string, { count: number; lastOpenedAt: number }> };
export function sortToolsByPopularity<T extends { id: string; defaultWeight?: number; order: number }>(tools: T[], stats: { tools: Record<string, { count: number; lastOpenedAt: number }> }, now?: number): T[];
