export const NETWORK_API_PATHS: {
  lookup: "/api/network/ip-lookup";
  rdap: "/api/network/ip-rdap";
};
export const NETWORK_ERROR_CODES: string[];
export const IPV4_SPECIAL_RANGES_REVIEWED_AT: string;
export function parseIpv4(input: string): { ok: true; data: { value: string; numeric: bigint } } | { ok: false; reason: string };
export function parseIpv4Octets(octets: string[]): { ok: true; data: { value: string; numeric: bigint } } | { ok: false; reason: string };
export function shouldAutoAdvanceIpv4Octet(input: { value: string; inputType?: string; index: number }): boolean;
export function ipv4ToString(numeric: bigint): string;
export function parseIpv4Integer(input: string): { ok: true; data: { numeric: bigint } } | { ok: false; reason: string };
export function parseIpv4Binary(input: string): { ok: true; data: { numeric: bigint; binary: string } } | { ok: false; reason: string };
export function parseIpv4Hex(input: string): { ok: true; data: { numeric: bigint } } | { ok: false; reason: string };
export function formatIpv4Binary(numeric: bigint, grouped?: boolean): string;
export function formatIpv4Hex(numeric: bigint): string;
export function prefixToMask(prefix: string | number): { ok: true; data: { prefix: number; mask: bigint } } | { ok: false; reason: string };
export function parseSubnetMask(input: string): { ok: true; data: { prefix: number; mask: bigint } } | { ok: false; reason: string };
export function parseIpv4Cidr(input: string): { ok: true; data: { ip: bigint; prefix: number } } | { ok: false; reason: string };
export function calculateIpv4Subnet(input: { ip: string | bigint; prefix: string | number }): { ok: true; data: Record<string, unknown> } | { ok: false; reason: string };
export function requiredHostsToPrefix(hosts: string): { ok: true; data: { prefix: number; total: bigint; usable: bigint } } | { ok: false; reason: string };
export function sameIpv4Subnet(ipA: string, ipB: string, prefix: string | number): { ok: true; data: { same: boolean } } | { ok: false; reason: string };
export function cidrToIpv4Range(cidr: string): { ok: true; data: { start: string; end: string; total: bigint; cidr: string } } | { ok: false; reason: string };
export function ipv4RangeToCidrs(startInput: string, endInput: string): { ok: true; data: { cidrs: string[] } } | { ok: false; reason: string };
export function classifyIpv4(input: string | bigint): { type: string; label: string; publicQuery?: boolean; cidr: string };
export function convertIpv4(input: string, source: string): { ok: true; data: Record<string, unknown> } | { ok: false; reason: string };
export function parseIpv6(input: string): { ok: true; data: { numeric: bigint; words: number[] } } | { ok: false; reason: string };
export function ipv6ToExpanded(input: string | bigint): { ok: true; data: { expanded: string; words: string[] } } | { ok: false; reason: string };
export function ipv6ToCompressed(input: string | bigint): { ok: true; data: { compressed: string } } | { ok: false; reason: string };
export function ipv6PrefixRange(input: string, prefix: string | number): { ok: true; data: { prefix: number; start: string; end: string; total: bigint } } | { ok: false; reason: string };
export function classifyIpv6(input: string | bigint): { type: string; label: string; publicQuery: boolean };
export function normalizeIp(input: string): { ok: true; data: { version: number; ip: string; numeric: bigint; classification: { type: string; label: string; publicQuery?: boolean } } } | { ok: false; reason: string };
export function isPublicQueryableIp(input: string): { ok: true; data: { version: number; ip: string; numeric: bigint; classification: { type: string; label: string; publicQuery?: boolean } } } | { ok: false; reason: string };
export function createApiResponse(body: unknown, status?: number): Response;
export function readStrictJsonRequest(request: Request, options?: { maxBytes?: number; allowedFields?: string[] }): Promise<{ ok: true; data: { mode: "current" } | { mode: "ip"; ip: string } } | { ok: false; error: { code: string; message: string; retryable: boolean } }>;
export function failApi(code: string, retryable?: boolean): { ok: false; error: { code: string; message: string; retryable: boolean } };
export function handleIpLookupRequest(request: Request, options?: { provider?: { lookup(input: unknown): Promise<unknown> }; currentProvider?: { lookup(): Promise<unknown> }; now?: () => Date }): Promise<Response>;
export function handleRdapRequest(request: Request, options?: { provider?: { lookup(input: unknown): Promise<unknown> }; now?: () => Date }): Promise<Response>;
