import { TOOL_CONTENT_EN } from "./tool-content.en.js";

const localize = (id, content) => ({
  ...content,
  references: TOOL_CONTENT_EN[id].references,
  reviewedAt: TOOL_CONTENT_EN[id].reviewedAt,
});

export const TOOL_CONTENT_ZH_TW = {
  length: localize("length", {
    summary: "以公尺為共同基準，轉換常見公制、英制與美制長度單位。",
    introduction: "長度轉換支援公尺、公里、公分、毫米、英寸、英尺、碼與英里，適合處理圖面、行程或商品規格使用不同單位的情況。",
    useCases: ["比較以公尺和英尺標示的房間或家具尺寸。", "在公里和英里之間換算道路距離。"],
    steps: ["輸入有限的長度數值。", "選擇輸入單位與目標單位。", "檢查結果並視需要複製。"],
    example: { title: "公尺轉英尺", description: "輸入 1 公尺並選擇英尺，結果約為 3.280839895 英尺。" },
    principles: ["每個單位都以公尺表示固定換算因子；輸入先乘來源因子，再除以目標因子。"],
    limitations: ["顯示結果最多保留 10 位小數，精密工作應保留原始量測值。", "本工具只轉換長度，不會自動將因子平方或立方來轉換面積、體積。"],
    faqs: [
      { question: "1 公尺等於多少英尺？", answer: "工具採用國際英尺的精確定義 0.3048 公尺，因此 1 公尺約為 3.280839895 英尺。" },
      { question: "可以輸入負數嗎？", answer: "可以輸入任何有限數值，但負長度在多數實際情境中沒有物理意義。" },
    ],
    aliases: ["距離轉換", "公尺轉英尺", "公里轉英里", "m 轉 ft"],
    keywords: ["長度", "距離", "公尺", "英尺", "英里", "碼"],
  }),
  weight: localize("weight", {
    summary: "透過公斤基準轉換公斤、公克、毫克、磅、盎司與公噸。",
    introduction: "重量轉換適合日常質量單位換算。雖然日常用語常說「重量」，這裡以固定因子轉換的是質量。",
    useCases: ["把包裹質量由公斤換算為磅。", "在公克與盎司之間轉換食譜用量。"],
    steps: ["輸入有限的質量數值。", "選擇來源與目標單位。", "檢查並複製結果。"],
    example: { title: "公斤轉磅", description: "輸入 1 公斤，結果約為 2.204622622 磅。" },
    principles: ["所有數值都透過公斤換算；國際常衡磅以 0.45359237 公斤計算。"],
    limitations: ["工具不考慮當地重力，因此不計算以牛頓表示的力。", "顯示值可能經過捨入，商業秤重亦可能受計量法規約束。"],
    faqs: [
      { question: "「噸」是指哪一種噸？", answer: "是 1,000 公斤的公噸，不是美制短噸或英制長噸。" },
      { question: "磅與盎司採用常衡制嗎？", answer: "是，現有因子採常見的國際常衡磅與盎司。" },
    ],
    aliases: ["質量轉換", "公斤轉磅", "公克轉盎司", "kg 轉 lb"],
    keywords: ["重量", "質量", "公斤", "磅", "盎司", "公噸"],
  }),
  temperature: localize("temperature", {
    summary: "使用標準偏移公式轉換攝氏、華氏與克氏溫度。",
    introduction: "攝氏與華氏的零點不同，溫度換算不能只乘一個比例。本工具透過攝氏在攝氏、華氏和克氏之間轉換。",
    useCases: ["在攝氏與華氏之間換算天氣溫度。", "把實驗溫度由攝氏轉為克氏。" ],
    steps: ["輸入有限溫度。", "選擇目前溫標和目標溫標。", "檢查轉換結果。"],
    example: { title: "水的冰點", description: "輸入 0 °C，轉換為 32 °F 或 273.15 K。" },
    principles: ["華氏公式為 °F = °C × 9/5 + 32；克氏公式為 K = °C + 273.15。"],
    limitations: ["介面不會阻止低於絕對零度的值；絕對零度是 −273.15 °C、−459.67 °F 或 0 K，這類輸入會得到數學結果但不具物理意義。", "不處理量測不確定度或材料隨溫度變化的性質。"],
    faqs: [
      { question: "克氏為什麼沒有度數符號？", answer: "SI 單位名稱是 kelvin，符號為 K，不使用度數符號。" },
      { question: "攝氏和華氏何時數值相同？", answer: "兩者在 −40 時數值相同。" },
    ],
    aliases: ["攝氏轉華氏", "華氏轉攝氏", "克氏轉換", "溫標轉換"],
    keywords: ["溫度", "攝氏", "華氏", "克氏", "絕對零度"],
  }),
  area: localize("area", {
    summary: "透過平方公尺轉換公制平方單位、公頃、英畝與平方英尺。",
    introduction: "面積轉換涵蓋土地、室內與圖面常用單位，所有選項都作為面積單位並透過平方公尺換算。",
    useCases: ["比較以英畝和公頃表示的土地面積。", "把房間面積由平方公尺轉為平方英尺。"],
    steps: ["輸入有限面積。", "選擇輸入和目標面積單位。", "檢查並複製結果。"],
    example: { title: "平方公尺轉平方英尺", description: "1 平方公尺約為 10.763910417 平方英尺。" },
    principles: ["面積因子來自長度關係的平方，例如 1 平方英尺等於 0.09290304 平方公尺。"],
    limitations: ["不會根據邊長推算不規則形狀面積。", "測量或法定土地紀錄可能使用地區定義或捨入規則。"],
    faqs: [
      { question: "1 公頃是多少平方公尺？", answer: "1 公頃等於 10,000 平方公尺。" },
      { question: "英畝一定是正方形嗎？", answer: "不是。英畝是 4,046.8564224 平方公尺的面積，可以有不同形狀。" },
    ],
    aliases: ["土地面積轉換", "平方公尺轉平方英尺", "英畝轉公頃", "平方單位轉換"],
    keywords: ["面積", "平方公尺", "平方英尺", "英畝", "公頃"],
  }),
  volume: localize("volume", {
    summary: "轉換公升、毫升、立方公尺及常見美制液體體積單位。",
    introduction: "體積轉換把公制單位和美制加侖、夸脫、品脫及杯放在一起，所有換算都以公升為共同基準。",
    useCases: ["把容器容量由公升換算為美制加侖。", "在毫升和美制杯之間轉換烹飪用量。"],
    steps: ["輸入有限體積。", "選擇來源與目標單位。", "讀取並複製結果。"],
    example: { title: "公升轉美制加侖", description: "1 公升約為 0.264172052 美制加侖。" },
    principles: ["1 立方公尺等於 1,000 公升；1 美制液體加侖以 3.785411784 公升計算。"],
    limitations: ["加侖、夸脫、品脫和杯均為美制液體單位，不是英制單位。", "工具只轉換體積，無法在不知道密度時轉成質量。"],
    faqs: [
      { question: "這裡使用哪一種加侖？", answer: "使用美制液體加侖，未提供容量不同的英制加侖。" },
      { question: "公升能直接換成公斤嗎？", answer: "不能，必須先知道物質密度，而本工具不要求此資料。" },
    ],
    aliases: ["公升轉換", "公升轉加侖", "毫升轉杯", "液體體積"],
    keywords: ["體積", "公升", "毫升", "加侖", "杯", "立方公尺"],
  }),
  speed: localize("speed", {
    summary: "轉換公尺／秒、公里／小時、英里／小時、節與英尺／秒。",
    introduction: "速度轉換適用於道路、航海、航空和科學情境，所有單位都透過公尺／秒換算。",
    useCases: ["比較公里／小時和英里／小時的行車速度。", "把以節表示的航速換算為公尺／秒。"],
    steps: ["輸入有限速度。", "選擇目前單位與目標單位。", "檢查轉換結果。"],
    example: { title: "公里／小時轉英里／小時", description: "100 km/h 約為 62.137119224 mph。" },
    principles: ["速度是距離除以時間，固定因子先把每個選項表示為公尺／秒。"],
    limitations: ["只轉換速度大小，不含方向、加速度、風或水流。", "顯示捨入不適合導航或安全關鍵計算。"],
    faqs: [
      { question: "「節」是什麼？", answer: "1 節是每小時 1 海里，本工具以約 0.5144444444 公尺／秒計算。" },
      { question: "mph 是英里／小時嗎？", answer: "是，使用國際英里和 3,600 秒的小時。" },
    ],
    aliases: ["速度單位轉換", "公里時轉英里時", "kmh 轉 mph", "節轉換"],
    keywords: ["速度", "公尺每秒", "公里每小時", "英里每小時", "節"],
  }),
  time: localize("time", {
    summary: "以固定秒數因子轉換毫秒至週的持續時間。",
    introduction: "時間轉換處理經過時長而不是日曆日期，毫秒、秒、分鐘、小時、天和週都透過秒換算。",
    useCases: ["把程式逾時由毫秒轉成秒。", "把專案時長由小時轉成天或週。"],
    steps: ["輸入有限時長。", "選擇來源和目標時長單位。", "檢查結果。"],
    example: { title: "小時轉分鐘", description: "1 小時等於 60 分鐘。" },
    principles: ["採用 1 分鐘 = 60 秒、1 小時 = 3,600 秒、1 天 = 86,400 秒、1 週 = 604,800 秒。"],
    limitations: ["天和週都是固定時長，不考慮日光節約時間、閏秒、月份和日曆規則。", "這不是時區或排程工具。"],
    faqs: [
      { question: "每一天都按 24 小時計算嗎？", answer: "是，本轉換器固定以 86,400 秒計算一天。" },
      { question: "可以轉換月份或年份嗎？", answer: "不可以，因為其日曆長度不固定。" },
    ],
    aliases: ["時長轉換", "小時轉分鐘", "秒轉毫秒", "天轉週"],
    keywords: ["時間", "時長", "毫秒", "秒", "小時", "天", "週"],
  }),
  storage: localize("storage", {
    summary: "依本工具的二進位 1,024 進位轉換 B、KB、MB、GB、TB 與 PB。",
    introduction: "資料儲存轉換涵蓋 B 至 PB。現有實作每一級都乘 1,024，但介面沿用常見的 KB、MB、GB 標示。",
    useCases: ["依本工具規則把 GB 換算為 MB。", "在較大和較小的二進位容量標示之間轉換。"],
    steps: ["輸入有限容量。", "選擇目前標示和目標標示。", "查看結果並確認對方系統採用相同慣例。"],
    example: { title: "GB 轉 MB", description: "在本工具中，1 GB 轉換為 1,024 MB。" },
    principles: ["實作採二進位比例：1 KB = 1,024 B，1 MB = 1,024 KB，之後每級繼續乘 1,024。"],
    limitations: ["SI 十進位前綴通常表示 1,000 的次方，IEC 二進位前綴使用 KiB、MiB、GiB。本介面以 KB、MB、GB 表示 1,024 進位，和其他系統比較前要確認慣例。", "不讀取檔案、壓縮率、檔案系統額外空間或可用容量。"],
    faqs: [
      { question: "為什麼 1 GB 等於 1,024 MB？", answer: "因為現有實作每一級使用 1,024 的二進位因子。" },
      { question: "與硬碟廠商的容量相同嗎？", answer: "不一定。硬碟廠商常用 1,000 進位，因此顯示值可能不同。" },
    ],
    aliases: ["檔案大小轉換", "GB 轉 MB", "位元組轉換", "二進位容量"],
    keywords: ["儲存", "位元組", "KB", "MB", "GB", "1024", "二進位前綴"],
  }),
  json: localize("json", {
    summary: "使用瀏覽器 JSON 解析器在本機格式化、壓縮與驗證 JSON。",
    introduction: "JSON 工具會解析輸入以驗證語法；格式化模式採兩個空格縮排，壓縮模式移除非必要空白。格式化與壓縮改變呈現方式，驗證則判斷文字是否符合 JSON 語法。",
    useCases: ["把緊湊的 API 回應整理成容易閱讀的結構。", "儲存前壓縮有效的設定片段。"],
    steps: ["貼上或輸入 JSON。", "選擇「格式化」或「壓縮」。", "解析成功後檢查並複製；失敗時查看本機錯誤訊息。"],
    example: { title: "格式化物件", description: "輸入 {\"active\":true,\"count\":2} 後，格式化模式會輸出兩空格縮排的多行物件。" },
    principles: ["實作以 JSON.parse 驗證，再以 JSON.stringify 輸出；空白不影響 JSON 值的語意。"],
    limitations: ["註解、尾端逗號、未加引號的鍵、NaN 和 Infinity 都不是有效 JSON。", "JavaScript 數值精度有限，超大整數可能失真。"],
    faqs: [
      { question: "格式化會改變資料嗎？", answer: "對有效 JSON，主要改變空白和縮排；JavaScript 數值精度限制仍存在。" },
      { question: "壓縮等於加密嗎？", answer: "不是，只會移除非必要空白，文字仍可讀取。" },
      { question: "JSON 會上傳嗎？", answer: "不會，解析和輸出都在目前瀏覽器進行。" },
    ],
    aliases: ["JSON 格式化", "JSON 驗證", "JSON 壓縮", "JSON 美化"],
    keywords: ["JSON", "格式化", "壓縮", "驗證", "解析器", "開發工具"],
  }),
  base64: localize("base64", {
    summary: "把 Unicode 文字編碼為標準 Base64，或解碼回文字。",
    introduction: "Base64 工具先將文字轉為 UTF-8 位元組，再進行標準 Base64 編碼；解碼時反向處理。Base64 以可列印字元表示位元組，不是安全機制。",
    useCases: ["把短 Unicode 文字編碼後放入只接受文字的欄位。", "解碼標準 Base64 字串以查看 UTF-8 文字。"],
    steps: ["編碼時輸入文字，解碼時輸入 Base64。", "選擇編碼或解碼方向。", "檢查並複製本機結果。"],
    example: { title: "Unicode 文字", description: "編碼 Hello 世界時，字元先轉為 UTF-8 位元組，再產生帶填補的標準 Base64。" },
    principles: ["使用 TextEncoder 和 TextDecoder 處理 UTF-8，並採瀏覽器 btoa/atob 的標準 Base64 字母表與填補。"],
    limitations: ["Base64 是編碼而不是加密，任何人都能解碼內容。", "目前不是 URL 和檔名安全的 Base64url。", "任意二進位資料解碼後不一定是有效或可讀的 UTF-8 文字。"],
    faqs: [
      { question: "為什麼輸出更長？", answer: "Base64 通常以 4 個字元表示 3 個輸入位元組，並可能加入填補。" },
      { question: "可以保護密碼嗎？", answer: "不可以，Base64 沒有保密能力。" },
      { question: "支援中文嗎？", answer: "支援，文字會先轉成 UTF-8 位元組。" },
    ],
    aliases: ["Base64 編碼", "Base64 解碼", "b64", "Unicode Base64"],
    keywords: ["Base64", "編碼", "解碼", "UTF-8", "文字", "非加密"],
  }),
  url: localize("url", {
    summary: "依 JavaScript 百分比編碼規則處理一個 URL 元件。",
    introduction: "URL 編解碼會把整段輸入視為一個 URL 元件，不會把完整 URL 拆成通訊協定、主機、路徑和查詢參數。",
    useCases: ["編碼含空格或非 ASCII 字元的查詢參數值。", "解碼百分比編碼的路徑片段或參數值。"],
    steps: ["編碼時輸入一般元件文字，解碼時輸入已編碼文字。", "選擇方向。", "檢查結果；錯誤跳脫序列會顯示無效。"],
    example: { title: "編碼元件", description: "a b/世界 會變成 a%20b%2F%E4%B8%96%E7%95%8C，因為斜線也被視為元件資料。" },
    principles: ["編碼使用 JavaScript encodeURIComponent，解碼使用 decodeURIComponent，並處理 UTF-8 百分比序列。"],
    limitations: ["不解析或驗證完整 URL，/、?、&、= 等保留分隔符也會被編碼。", "加號不會自動變成空格，HTML 表單編碼規則不同。", "錯誤的百分比跳脫會被拒絕。"],
    faqs: [
      { question: "為什麼斜線也被編碼？", answer: "因為 encodeURIComponent 把整段輸入視為一個元件，斜線不是路徑分隔符。" },
      { question: "解碼會驗證完整網址嗎？", answer: "不會，只處理輸入文字中的百分比跳脫。" },
    ],
    aliases: ["百分比編碼", "URL 編碼", "URL 解碼", "encodeURIComponent"],
    keywords: ["URL", "URI", "百分比編碼", "元件", "decodeURIComponent"],
  }),
  uuid: localize("uuid", {
    summary: "使用瀏覽器加密隨機來源產生隨機 UUID v4。",
    introduction: "UUID 產生器在目前瀏覽器建立版本 4 UUID，適合在不便使用中央流水號時產生識別碼。",
    useCases: ["為測試資料或本機紀錄建立 ID。", "開發時產生請求或關聯識別碼。"],
    steps: ["開啟工具取得初始 UUID。", "按下產生以替換為新的 UUID v4。", "複製識別碼。"],
    example: { title: "UUID v4 結構", description: "產生值採 8-4-4-4-12 十六進位布局，版本和變體位由瀏覽器設定。" },
    principles: ["實作呼叫 crypto.randomUUID()，由瀏覽器的加密安全隨機來源產生 UUID 版本 4。"],
    limitations: ["UUID 只是識別碼，不是密碼、存取權杖或紀錄存在證明。", "碰撞機率極低，但不是數學上的絕對唯一保證。"],
    faqs: [
      { question: "會產生哪個版本？", answer: "只產生 UUID 版本 4。" },
      { question: "能從中讀取產生時間嗎？", answer: "不能，版本 4 是隨機識別碼，不含時間。" },
    ],
    aliases: ["GUID 產生器", "UUID v4", "隨機 ID", "唯一識別碼"],
    keywords: ["UUID", "GUID", "版本 4", "隨機", "識別碼", "加密隨機"],
  }),
  timestamp: localize("timestamp", {
    summary: "在 Unix 秒／毫秒、ISO UTC 文字與本機日期時間之間轉換。",
    introduction: "數值輸入會辨識為秒或毫秒並顯示 ISO 8601 UTC 文字；datetime-local 輸入則依瀏覽器本機時區轉為 Unix 秒和毫秒。",
    useCases: ["把 API 時間戳查看為可讀的 UTC 時間。", "為選定的本機日期時間產生秒和毫秒值。"],
    steps: ["輸入時間戳或選擇本機日期時間。", "查看 ISO UTC 或秒／毫秒結果。", "使用互換按鈕在兩個區域間轉移有效值。"],
    example: { title: "Unix 時間範例", description: "1704067200 秒會轉換為 2024-01-01T00:00:00.000Z。" },
    principles: ["JavaScript Date 以 Unix 紀元後的毫秒表示時間；toISOString 輸出 UTC，datetime-local 依瀏覽器本機時區解讀。"],
    limitations: ["絕對值小於 100,000,000,000 時按秒處理，達到或超過該門檻時按毫秒處理，特殊歷史或遠期數值可能有歧義。", "datetime-local 不含時區後綴，會使用目前瀏覽器時區。", "JavaScript Date 不表示閏秒。"],
    faqs: [
      { question: "如何辨識秒和毫秒？", answer: "目前實作以絕對值 100,000,000,000 作為門檻。" },
      { question: "ISO 結果為何以 Z 結尾？", answer: "Z 表示 UTC，工具會把該時刻轉成 UTC 文字。" },
      { question: "日期時間輸入使用哪個時區？", answer: "使用瀏覽器目前的本機時區。" },
    ],
    aliases: ["Unix 時間戳", "紀元轉換", "秒轉日期", "毫秒轉日期"],
    keywords: ["時間戳", "Unix", "紀元", "ISO 8601", "UTC", "時區", "毫秒"],
  }),
  case: localize("case", {
    summary: "把文字轉成大寫、小寫、標題式或基礎 camelCase。",
    introduction: "文字大小寫轉換使用瀏覽器的 Unicode 大小寫操作和簡單詞形規則，適合在本機處理標籤、標題和識別碼。",
    useCases: ["統一標題的大寫或小寫形式。", "把空格、底線或連字號分隔的文字轉成基礎 camelCase。"],
    steps: ["輸入或貼上文字。", "選擇 upper、lower、title 或 camel。", "檢查並複製結果。"],
    example: { title: "基礎駝峰式", description: "Lite tools_example 會變成 liteToolsExample。" },
    principles: ["大寫和小寫使用瀏覽器本地化規則；標題模式處理 Unicode 單字；駝峰模式移除空格、底線與連字號後大寫下一個字元。"],
    limitations: ["標題模式不了解各語言編輯規範的小詞例外。", "駝峰模式不會辨識所有標點或縮寫慣例。", "某些 Unicode 大小寫轉換會改變字串長度。"],
    faqs: [
      { question: "標題模式會遵循新聞標題規範嗎？", answer: "不會，只會依規則大寫詞首。" },
      { question: "駝峰模式會保留縮寫嗎？", answer: "不一定，它沒有縮寫字典。" },
    ],
    aliases: ["大寫轉換", "小寫轉換", "標題格式", "駝峰格式"],
    keywords: ["文字大小寫", "大寫", "小寫", "標題", "camelCase", "Unicode"],
  }),
  text: localize("text", {
    summary: "在本機統計 Unicode 碼點、空白分隔詞組與文字行數。",
    introduction: "字數統計依目前實作的明確規則回報字元、字詞和行數，適合快速檢查文字，不等同語言學或出版統計。",
    useCases: ["快速查看短稿長度。", "統計貼上筆記或小段文字的行數。"],
    steps: ["輸入或貼上文字。", "查看即時字元、字詞和行數。", "需要時複製三項統計摘要。"],
    example: { title: "中英混合文字", description: "one two 換行後輸入 三，會得到 9 個字元、3 個空白分隔詞組和 2 行。" },
    principles: ["字元按 Unicode 碼點統計；字詞是一個或多個空白字元分隔的非空群組；行按 CRLF、CR 或 LF 分隔，空輸入為 0 行。"],
    limitations: ["沒有空格的中文句子會計為一個字詞群組，不會自動斷詞。", "一個視覺字形或 emoji 序列可能包含多個 Unicode 碼點，因此可能算多個字元。", "不統計頁數、句子、閱讀時間或位元組數。"],
    faqs: [
      { question: "空格算字元嗎？", answer: "算，字元統計包含空白碼點。" },
      { question: "中文詞數如何計算？", answer: "只按空白邊界，連續無空格中文算一個詞組。" },
      { question: "末尾換行會增加行數嗎？", answer: "輸入以換行結束時，分隔規則可能產生一個末尾空行。" },
    ],
    aliases: ["字元統計", "詞數統計", "行數統計", "文字統計"],
    keywords: ["字數", "字元", "字詞", "行數", "空白", "Unicode"],
  }),
  color: localize("color", {
    summary: "把 HEX 轉成 RGB，或把 RGB 色頻值轉成 HEX 與 HSL。",
    introduction: "顏色轉換支援三位或六位 HEX，以及紅、綠、藍數值色頻，輸出 CSS 風格的 RGB、HEX 和 HSL。",
    useCases: ["查看設計 HEX 顏色的 RGB 色頻。", "從 RGB 數值產生 HEX 和 HSL 表示。"],
    steps: ["輸入 HEX 或 0 至 255 的 RGB 色頻。", "查看對應顏色格式。", "複製產生的文字。"],
    example: { title: "綠色範例", description: "#187b69 會轉為 rgb(24, 123, 105)，相同 RGB 也會產生 #187b69 和 HSL。" },
    principles: ["HEX 以兩位十六進位表示每個 RGB 色頻；HSL 依正規化 RGB 的最大與最小值計算並取整數。"],
    limitations: ["產生 HEX 時 RGB 會四捨五入為整數。", "不處理透明度、廣色域、色彩描述檔、LAB 或 LCH。", "HSL 取整可能使往返轉換不完全一致。"],
    faqs: [
      { question: "支援三位 HEX 嗎？", answer: "支援，例如 #abc 會展開為 #aabbcc。" },
      { question: "RGB 超出範圍會被截斷嗎？", answer: "不會，低於 0 或高於 255 會被判定無效。" },
    ],
    aliases: ["HEX 轉 RGB", "RGB 轉 HEX", "RGB 轉 HSL", "CSS 顏色轉換"],
    keywords: ["顏色", "HEX", "RGB", "HSL", "CSS", "調色盤"],
  }),
  percentage: localize("percentage", {
    summary: "計算一個基準數值的指定百分比。",
    introduction: "百分比計算回答「V 的 P% 是多少」，直接執行乘法，接受有限的正數和負數。",
    useCases: ["計算稅額或小費金額。", "求一個量測值的 12.5% 等比例數值。"],
    steps: ["輸入百分比。", "輸入基準數值。", "查看並複製結果。"],
    example: { title: "百分之十", description: "250 的 10% 是 25。" },
    principles: ["公式為：結果 = 百分比 ÷ 100 × 基準數值。"],
    limitations: ["不會自動計算百分比變化、反向百分比、利潤率或加總後的總數。", "允許負數和超過 100% 的值，因為一般算術中可能有意義。"],
    faqs: [
      { question: "結果包含原數值嗎？", answer: "不包含，只回傳百分比對應的數值。" },
      { question: "百分比可以超過 100 嗎？", answer: "可以，目前實作接受任何有限百分比。" },
    ],
    aliases: ["數值百分比", "百分比工具", "求百分之幾", "percent 計算"],
    keywords: ["百分比", "比例", "基準數值", "計算"],
  }),
  discount: localize("discount", {
    summary: "依原價和折扣率計算折後價與省下金額。",
    introduction: "折扣計算對非負原價套用一次百分比折扣，同時顯示折後價和省下金額。",
    useCases: ["購物前核對促銷價格。", "比較某個折扣百分比可省下多少。"],
    steps: ["輸入原價。", "輸入 0 至 100 的折扣率。", "查看折後價和省下金額。"],
    example: { title: "八五折", description: "原價 100、折扣率 15% 時，折後價是 85，省下 15。" },
    principles: ["折後價 = 原價 × (1 − 折扣率 ÷ 100)；省下金額 = 原價 × 折扣率 ÷ 100。"],
    limitations: ["不含稅費、運費、折價券、階梯折扣或匯率。", "結果只作數值參考，不是金融建議或商家報價。"],
    faqs: [
      { question: "折扣率可以超過 100% 嗎？", answer: "不可以，低於 0 或高於 100 會被拒絕。" },
      { question: "工具知道貨幣嗎？", answer: "不知道，只要輸入和結果採同一貨幣即可。" },
    ],
    aliases: ["折後價計算", "促銷價格", "優惠計算", "省下金額"],
    keywords: ["折扣", "促銷", "價格", "省下", "百分比"],
  }),
  bmi: localize("bmi", {
    summary: "用公斤和公分計算成人 BMI 一般參考值。",
    introduction: "BMI 計算把公斤體重除以公尺身高的平方。BMI 是群體篩檢指標，不能直接量測身體組成，也不能診斷健康狀況。",
    useCases: ["以公制資料計算成人 BMI 一般參考。", "核對與專業人員討論的 BMI 算式。"],
    steps: ["輸入體重（公斤）。", "輸入身高（公分）。", "查看 BMI 數值和健康提示。"],
    example: { title: "公制 BMI", description: "體重 70 公斤、身高 175 公分時，BMI 約為 22.9。" },
    principles: ["BMI = 體重（kg）÷ 身高²（m²），實作先把公分除以 100 轉成公尺。"],
    limitations: ["結果僅供一般資訊參考，不構成醫療診斷。", "BMI 不區分肌肉、脂肪、骨骼、年齡、性別、族群、懷孕或個別臨床情況。", "工具不判定成人分級；兒童需依年齡與性別的生長參考評估。"],
    faqs: [
      { question: "工具會診斷過重或肥胖嗎？", answer: "不會，只回傳 BMI 算術值。" },
      { question: "兒童能用相同方式解讀嗎？", answer: "不能，兒童與青少年需依年齡和性別評估。" },
      { question: "為什麼要轉換公分？", answer: "BMI 公式使用公尺，因此先將公分除以 100。" },
    ],
    aliases: ["身體質量指數", "BMI 查詢", "公斤公分 BMI", "健康計算"],
    keywords: ["BMI", "身體質量指數", "體重", "身高", "健康", "非診斷"],
  }),
  compound: localize("compound", {
    summary: "依本金、年利率、年數和每月複利估算成長。",
    introduction: "複利計算假設每年計息 12 次，回傳期末金額及其與本金的差額。",
    useCases: ["探索簡化的儲蓄成長情境。", "比較名目年利率經過若干年每月複利後的結果。"],
    steps: ["輸入本金。", "輸入年利率和年數。", "查看估算金額和利息。"],
    example: { title: "每月複利", description: "本金 1,000、年利率 12%、1 年，每月複利後約為 1,126.83。" },
    principles: ["實作公式為 A = P(1 + r/12)^(12t)：年利率先除以 100，每年固定 12 個複利週期。"],
    limitations: ["介面固定每年複利 12 次，不含追加投入、提領、費用、稅款、通膨、變動利率或計息日規則。", "結果是數學估算，不構成金融建議或收益承諾。", "負利率雖可輸入，但某些組合可能得到非有限結果。"],
    faqs: [
      { question: "可以選擇按年或按日複利嗎？", answer: "不可以，目前介面固定按月複利。" },
      { question: "包含定期投入嗎？", answer: "不包含，只計算一次初始本金。" },
      { question: "顯示利息是單利嗎？", answer: "不是，是最終複利金額減去本金。" },
    ],
    aliases: ["複利計算", "每月複利", "投資成長", "利息計算"],
    keywords: ["複利", "本金", "年利率", "年數", "每月", "利息"],
  }),
  datecalc: localize("datecalc", {
    summary: "計算兩個瀏覽器日期輸入之間的絕對經過天數。",
    introduction: "日期間隔把兩個日期轉成 JavaScript 時間戳，再回傳按 24 小時單位計算並取整數的絕對差值。",
    useCases: ["查看兩個一般日期相隔多少天。", "不必手動數日曆即可比較兩個截止日。"],
    steps: ["選擇開始日期。", "選擇結束日期。", "查看絕對經過天數。"],
    example: { title: "一月間隔", description: "由 2024-01-01 到 2024-01-31 回傳 30 天。" },
    principles: ["實作取兩個 Date 時間戳差值的絕對值，除以 86,400,000 毫秒並四捨五入為整數。"],
    limitations: ["結果是經過差值，不會同時包含起訖日期；1 月 1 日至 1 月 31 日是 30 天而不是 31 天。", "瀏覽器日期解析、本機時區或日光節約時間可能影響特殊情況，因為實作按固定 24 小時除法。", "不計算工作日、假日、月份或排程。"],
    faqs: [
      { question: "日期順序有影響嗎？", answer: "沒有，工具使用絕對差值。" },
      { question: "會同時包含開始和結束日嗎？", answer: "不會，結果是兩者之間的經過間隔。" },
      { question: "會排除週末嗎？", answer: "不會，所有經過日同等處理。" },
    ],
    aliases: ["日期相差天數", "日期差", "天數間隔", "經過天數"],
    keywords: ["日期", "間隔", "差值", "天數", "經過", "時區"],
  }),
  qr: localize("qr", {
    summary: "在本機把文字或 URL 產生為可自訂的 QR Code PNG。",
    introduction: "QR Code 產生器在瀏覽器編碼輸入內容，可設定圖片尺寸、前景色與背景色，並下載 PNG；原始文字另有複製操作。",
    useCases: ["為公開網址產生 QR Code。", "把短文字編碼後在裝置之間傳遞。"],
    steps: ["輸入要編碼的完整文字或 URL。", "選擇 PNG 尺寸及高對比前景、背景顏色。", "以目標裝置試掃預覽，再下載 PNG。"],
    example: { title: "網址 QR Code", description: "輸入 https://example.com 會產生包含該文字的 QR Code，並提供 PNG 下載。" },
    principles: ["瀏覽器端 qrcode 程式庫選擇符號並繪製 PNG data URL。內容越多，通常需要的模組越多；圖片尺寸不變時單一模組會更小。"],
    limitations: ["介面拒絕空內容及超過 1,200 個字元的輸入，作為保守的可靠性限制；實際容量也受位元組長度和編碼模式影響。", "掃描相容性受對比、圖片尺寸、靜區、列印、相機和掃描軟體影響，最終檔案必須實測。", "QR Code 只儲存輸入內容，不會驗證網址安全性，也不會加密內容。"],
    faqs: [
      { question: "QR 內容會上傳嗎？", answer: "不會，圖片在目前瀏覽器產生。" },
      { question: "長內容為何較難掃描？", answer: "資料越多符號越密，在固定圖片尺寸下模組更小。" },
      { question: "什麼顏色最穩妥？", answer: "通常使用深色前景和淺色高對比背景。" },
    ],
    aliases: ["QR 產生器", "二維碼產生", "文字轉 QR", "網址 QR"],
    keywords: ["QR Code", "二維碼", "PNG", "掃描", "容量", "對比", "本機"],
  }),
};
