const SI_REFERENCE = {
  label: "BIPM SI Brochure",
  url: "https://www.bipm.org/en/publications/si-brochure",
};
const NIST_PERCENT_REFERENCE = {
  label: "NIST Guide for the Use of the International System of Units",
  url: "https://www.nist.gov/pml/special-publication-811",
};
const DATE_REFERENCE = {
  label: "ECMAScript Date objects",
  url: "https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-objects",
};
const reviewedAt = "2026-07-29";

export const TOOL_CONTENT_EN = {
  length: {
    summary: "Convert common metric, imperial, and US customary length units with a shared metre base.",
    introduction: "The length converter handles metres, kilometres, centimetres, millimetres, inches, feet, yards, and miles. It is useful when a measurement is supplied in a unit that does not match a drawing, journey plan, or product specification.",
    useCases: ["Compare room or furniture dimensions stated in metres and feet.", "Translate road distances between kilometres and miles."],
    steps: ["Enter a finite length value.", "Choose the unit used by the input and the unit required for the result.", "Review the converted value and copy it if needed."],
    example: { title: "Metres to feet", description: "Entering 1 metre and choosing feet returns approximately 3.280839895 feet." },
    principles: ["Each unit is represented as a fixed factor relative to one metre; the input is multiplied by its source factor and divided by the destination factor."],
    limitations: ["Displayed results are rounded to at most 10 fractional digits, so retain the raw source measurement for precision-sensitive work.", "This tool converts length only; it does not convert area or volume by applying squared or cubed factors."],
    faqs: [
      { question: "How many feet are in one metre?", answer: "The converter uses the exact international foot definition of 0.3048 metre, so one metre is about 3.280839895 feet." },
      { question: "Can I enter a negative length?", answer: "The calculator accepts any finite number, including negative values, although a negative physical length may not make sense for the task." },
    ],
    references: [SI_REFERENCE],
    aliases: ["distance converter", "meters to feet", "km to miles", "m to ft"],
    keywords: ["length", "distance", "metre", "meter", "foot", "mile", "yard"],
    reviewedAt,
  },
  weight: {
    summary: "Convert kilograms, grams, milligrams, pounds, ounces, and metric tons through a kilogram base.",
    introduction: "The weight converter provides everyday mass conversions between metric units and common pound or ounce values. Although everyday language often says weight, the fixed factors in this tool convert mass.",
    useCases: ["Convert a package mass from kilograms to pounds for a shipping form.", "Translate recipe quantities between grams and ounces."],
    steps: ["Enter a finite mass value.", "Select the source and destination units.", "Check and copy the converted number."],
    example: { title: "Kilograms to pounds", description: "Entering 1 kilogram and selecting pounds returns approximately 2.204622622 pounds." },
    principles: ["All values are converted through kilograms; one international avoirdupois pound is represented as 0.45359237 kilogram."],
    limitations: ["The tool does not account for local gravity and therefore does not calculate force in newtons.", "Results may be rounded for display, and commercial weighing rules can require regulated instruments."],
    faqs: [
      { question: "Does ton mean metric ton?", answer: "Yes. The t option is a metric ton of 1,000 kilograms, not a US short ton or UK long ton." },
      { question: "Are pounds and ounces avoirdupois units?", answer: "Yes. The implemented factors use the common international avoirdupois pound and ounce." },
    ],
    references: [SI_REFERENCE],
    aliases: ["mass converter", "kg to lb", "grams to ounces", "kilograms to pounds"],
    keywords: ["weight", "mass", "kilogram", "pound", "ounce", "metric ton"],
    reviewedAt,
  },
  temperature: {
    summary: "Convert Celsius, Fahrenheit, and kelvin values using the standard offset formulas.",
    introduction: "Temperature scales cannot be converted with a single multiplication factor because Celsius and Fahrenheit have different zero points. This tool converts through Celsius and supports Celsius, Fahrenheit, and kelvin.",
    useCases: ["Translate a weather forecast between Celsius and Fahrenheit.", "Convert a laboratory temperature from Celsius to kelvin."],
    steps: ["Enter a finite temperature.", "Select the current scale and destination scale.", "Review the converted result."],
    example: { title: "Freezing point of water", description: "Entering 0 °C and selecting Fahrenheit returns 32 °F; selecting kelvin returns 273.15 K." },
    principles: ["Fahrenheit is calculated as °F = °C × 9/5 + 32. Kelvin is calculated as K = °C + 273.15."],
    limitations: ["Values below absolute zero (−273.15 °C, −459.67 °F, or 0 K) are rejected; each boundary value itself is valid.", "The conversion does not model measurement uncertainty or temperature-dependent material behavior."],
    faqs: [
      { question: "Why does kelvin not use a degree symbol?", answer: "The SI unit name is kelvin and its symbol is K, without a degree sign." },
      { question: "At what value are Celsius and Fahrenheit equal?", answer: "Both scales have the same numerical value at −40." },
    ],
    references: [SI_REFERENCE],
    aliases: ["celsius to fahrenheit", "fahrenheit to celsius", "kelvin converter", "temperature scale"],
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin", "absolute zero"],
    reviewedAt,
  },
  area: {
    summary: "Convert square metric units, hectares, acres, and square feet through square metres.",
    introduction: "The area converter covers common land, floor, and drawing measurements. It treats every option as an area unit and converts through square metres.",
    useCases: ["Compare a property listing in acres with an area stated in hectares.", "Convert room floor area from square metres to square feet."],
    steps: ["Enter a finite area value.", "Select the input area unit and target unit.", "Review and copy the result."],
    example: { title: "Square metres to square feet", description: "Entering 1 square metre returns approximately 10.763910417 square feet." },
    principles: ["Area conversion factors are squared length relationships; for example, one square foot equals 0.09290304 square metre."],
    limitations: ["The tool does not infer irregular-shape area from dimensions.", "Surveying and legal land records may use jurisdiction-specific definitions or rounding rules."],
    faqs: [
      { question: "How many square metres are in a hectare?", answer: "One hectare is 10,000 square metres." },
      { question: "Is an acre a square with fixed side length?", answer: "An acre is an area of 4,046.8564224 square metres; its boundary can have many shapes." },
    ],
    references: [SI_REFERENCE],
    aliases: ["land area converter", "sqm to sqft", "acre to hectare", "square meter converter"],
    keywords: ["area", "square metre", "square foot", "acre", "hectare"],
    reviewedAt,
  },
  volume: {
    summary: "Convert litres, millilitres, cubic metres, and common US liquid volume units.",
    introduction: "The volume converter combines metric volume units with US gallons, quarts, pints, and cups. Every conversion uses litres as the common base.",
    useCases: ["Convert a container capacity from litres to US gallons.", "Translate a cooking quantity between millilitres and US cups."],
    steps: ["Enter a finite volume.", "Choose the source and destination units.", "Read and copy the converted value."],
    example: { title: "Litres to US gallons", description: "Entering 1 litre returns approximately 0.264172052 US gallon." },
    principles: ["One cubic metre equals 1,000 litres; one US liquid gallon is represented as 3.785411784 litres."],
    limitations: ["The gallon, quart, pint, and cup options are US liquid units, not imperial units.", "The tool converts volume and does not account for density when converting ingredients by mass."],
    faqs: [
      { question: "Which gallon does the tool use?", answer: "It uses the US liquid gallon. An imperial gallon has a different volume and is not offered." },
      { question: "Can litres be converted directly to kilograms?", answer: "Not without the substance density, which this volume-only tool does not request." },
    ],
    references: [SI_REFERENCE],
    aliases: ["liter converter", "litres to gallons", "ml to cups", "liquid volume"],
    keywords: ["volume", "litre", "millilitre", "gallon", "cup", "cubic metre"],
    reviewedAt,
  },
  speed: {
    summary: "Convert metres per second, kilometres per hour, miles per hour, knots, and feet per second.",
    introduction: "The speed converter translates common road, marine, aviation, and scientific speed units through metres per second.",
    useCases: ["Compare kilometres per hour with miles per hour for driving.", "Convert a marine speed in knots to metres per second."],
    steps: ["Enter a finite speed.", "Select its current unit and the desired unit.", "Review the converted result."],
    example: { title: "Kilometres per hour to miles per hour", description: "Entering 100 km/h returns approximately 62.137119224 mph." },
    principles: ["A speed is a distance divided by time. Fixed factors express every option in metres per second before conversion."],
    limitations: ["The tool converts scalar speed only and does not include direction, acceleration, wind, or current.", "Displayed rounding may be unsuitable for navigation or safety-critical calculations."],
    faqs: [
      { question: "What is a knot?", answer: "One knot is one nautical mile per hour and is represented here as 0.5144444444 metre per second." },
      { question: "Does mph mean miles per hour?", answer: "Yes. The option uses the international mile and a 3,600-second hour." },
    ],
    references: [SI_REFERENCE],
    aliases: ["velocity converter", "kph to mph", "kmh to mph", "knots converter"],
    keywords: ["speed", "metres per second", "kilometres per hour", "mph", "knot"],
    reviewedAt,
  },
  time: {
    summary: "Convert durations from milliseconds through weeks using fixed second factors.",
    introduction: "The time converter handles elapsed durations rather than calendar dates. Milliseconds, seconds, minutes, hours, days, and weeks are converted through seconds.",
    useCases: ["Translate an application timeout from milliseconds to seconds.", "Convert a project duration from hours to days or weeks."],
    steps: ["Enter a finite duration.", "Choose the source and destination duration units.", "Review the result."],
    example: { title: "Hours to minutes", description: "Entering 1 hour returns 60 minutes." },
    principles: ["The tool uses 1 minute = 60 seconds, 1 hour = 3,600 seconds, 1 day = 86,400 seconds, and 1 week = 604,800 seconds."],
    limitations: ["Days and weeks are fixed durations; daylight-saving changes, leap seconds, months, and calendar rules are not included.", "This is not a timezone or calendar scheduler."],
    faqs: [
      { question: "Is every day treated as 24 hours?", answer: "Yes. A day is fixed at 86,400 seconds in this converter." },
      { question: "Can I convert months or years?", answer: "No. Their calendar lengths vary, so they are intentionally not offered as fixed units." },
    ],
    references: [SI_REFERENCE],
    aliases: ["duration converter", "hours to minutes", "seconds to milliseconds", "days to weeks"],
    keywords: ["time", "duration", "millisecond", "second", "hour", "day", "week"],
    reviewedAt,
  },
  storage: {
    summary: "Convert bytes using distinct SI decimal kB–PB and IEC binary KiB–PiB units.",
    introduction: "The data storage converter distinguishes decimal storage labels from binary capacity labels instead of treating KB and KiB as interchangeable.",
    useCases: ["Compare decimal drive capacity with an operating system’s binary display.", "Translate a file size between SI and IEC units without changing the underlying byte count."],
    steps: ["Enter a finite storage quantity.", "Choose the current decimal or binary unit explicitly.", "Choose the destination unit and review the converted value."],
    example: { title: "GB and GiB", description: "1 GB equals 1,000 MB, while 1 GiB equals 1,024 MiB. One MiB equals 1.048576 MB." },
    principles: ["SI decimal units use powers of 1,000: 1 kB = 1,000 B. IEC binary units use powers of 1,024: 1 KiB = 1,024 B."],
    limitations: ["Results larger than JavaScript’s safe integer range are rejected instead of presenting an exact byte count that may be misleading.", "The tool converts capacity values only; it does not inspect files, filesystem overhead, compression, or available space."],
    faqs: [
      { question: "What is the difference between GB and GiB?", answer: "GB is decimal and equals 1,000,000,000 bytes; GiB is binary and equals 1,073,741,824 bytes." },
      { question: "Why can drive capacity and system display differ?", answer: "Drive vendors commonly use decimal units while some systems present binary quantities, so the numeric labels differ for the same byte count." },
    ],
    references: [
      { label: "IEC 80000-13 information units", url: "https://webstore.iec.ch/en/publication/87379" },
      SI_REFERENCE,
    ],
    aliases: ["file size converter", "gb to mb", "gib to mib", "bytes converter"],
    keywords: ["storage", "byte", "kilobyte", "kibibyte", "gigabyte", "gibibyte", "1000", "1024"],
    reviewedAt,
  },
  json: {
    summary: "Format, minify, and validate JSON text locally with the browser’s JSON parser.",
    introduction: "JSON tools format valid JSON with two-space indentation, minify it by removing insignificant whitespace, and validate syntax by parsing the input. Formatting and minifying change presentation, while validation determines whether the text follows JSON grammar.",
    useCases: ["Make a compact API response easier to read while debugging.", "Minify a valid configuration snippet before storing or transmitting it."],
    steps: ["Paste or type JSON into the input area.", "Choose Format for indentation or Minify for compact output.", "If parsing succeeds, review and copy the result; otherwise read the local parser error."],
    example: { title: "Format an object", description: "Input {\"active\":true,\"count\":2} becomes a multi-line object with two-space indentation in Format mode." },
    principles: ["The implementation calls JSON.parse for validation and JSON.stringify for output. Object member order is preserved as returned by the JavaScript parser, but JSON semantics do not rely on visual whitespace."],
    limitations: ["Comments, trailing commas, unquoted property names, NaN, and Infinity are not valid JSON and are rejected.", "Parsing can normalize number representation, and extremely large integers may lose precision in JavaScript numbers."],
    faqs: [
      { question: "Does formatting change the JSON data?", answer: "For valid JSON values it changes whitespace and indentation, not the parsed value. Number precision limits of JavaScript still apply." },
      { question: "Is minified JSON encrypted or compressed as a file?", answer: "No. Minification only removes insignificant whitespace; the text remains readable and is not encryption or general-purpose compression." },
      { question: "Is the pasted JSON uploaded?", answer: "No. This implementation parses and renders the text in the current browser." },
    ],
    references: [{ label: "RFC 8259 — JSON Data Interchange Format", url: "https://www.rfc-editor.org/info/rfc8259/" }],
    aliases: ["json formatter", "json validator", "json minifier", "pretty print json"],
    keywords: ["JSON", "format", "minify", "validate", "parser", "developer"],
    reviewedAt,
  },
  base64: {
    summary: "Encode Unicode text as standard Base64 or decode standard Base64 back to text.",
    introduction: "The Base64 tool converts text to UTF-8 bytes before standard Base64 encoding and reverses that process during decoding. Base64 is designed to represent bytes with printable characters; it is not a security mechanism.",
    useCases: ["Encode a short Unicode text value for a text-only field.", "Decode a standard Base64 string to inspect its UTF-8 text."],
    steps: ["Enter text for Encode or a Base64 string for Decode.", "Choose the direction; switching modes can reuse the valid output.", "Review and copy the local result."],
    example: { title: "Unicode text", description: "Encoding Hello 世界 first converts the characters to UTF-8 bytes, then produces a standard padded Base64 string." },
    principles: ["UTF-8 conversion is performed with TextEncoder and TextDecoder; the Base64 alphabet and padding follow the standard browser btoa/atob representation."],
    limitations: ["Base64 is an encoding, not encryption; anyone with a decoder can recover the content.", "The tool implements strictly padded standard Base64, not the Base64url alphabet used in some URLs and tokens.", "Decoded bytes must form valid UTF-8 text; arbitrary binary data is rejected."],
    faqs: [
      { question: "Why is the Base64 output longer?", answer: "Base64 represents each 3 input bytes with 4 printable characters, plus possible padding." },
      { question: "Can Base64 protect a password?", answer: "No. It provides no confidentiality and must not be treated as encryption." },
      { question: "Does it support Chinese text?", answer: "Yes. Text is converted to UTF-8 bytes before encoding and decoded back with UTF-8." },
    ],
    references: [{ label: "RFC 4648 — Base-N Encodings", url: "https://www.rfc-editor.org/info/rfc4648/" }],
    aliases: ["base64 encode", "base64 decode", "b64", "unicode base64"],
    keywords: ["Base64", "encode", "decode", "UTF-8", "text", "not encryption"],
    reviewedAt,
  },
  url: {
    summary: "Encode or decode one URL component with JavaScript percent-encoding rules.",
    introduction: "The URL encoder and decoder apply percent-encoding to text intended as a URL component, or decode valid percent-encoded sequences. It processes the entire input as one component rather than parsing a complete URL into scheme, host, path, and query fields.",
    useCases: ["Encode a query parameter value containing spaces or non-ASCII text.", "Decode a percent-encoded path or parameter value for inspection."],
    steps: ["Enter plain component text for Encode or encoded text for Decode.", "Choose the direction.", "Review and copy the result; malformed escape sequences produce an error."],
    example: { title: "Encode component text", description: "The input a b/世界 becomes a%20b%2F%E4%B8%96%E7%95%8C because the slash is encoded as part of the component." },
    principles: ["Encoding uses JavaScript encodeURIComponent and decoding uses decodeURIComponent, including UTF-8 percent sequences."],
    limitations: ["This tool does not parse or validate a complete URL and will encode reserved separators such as /, ?, &, and = when they appear in the input.", "A plus sign is not converted to a space; HTML form encoding has different rules.", "Malformed percent escapes are rejected."],
    faqs: [
      { question: "Why was the slash encoded?", answer: "encodeURIComponent treats the input as one component, so a slash is data rather than a path separator." },
      { question: "Does decoding validate the whole URL?", answer: "No. It only decodes percent escapes in the supplied text." },
    ],
    references: [{ label: "WHATWG URL Standard", url: "https://url.spec.whatwg.org/" }],
    aliases: ["percent encoder", "url encode", "url decode", "encodeURIComponent"],
    keywords: ["URL", "URI", "percent encoding", "component", "decodeURIComponent"],
    reviewedAt,
  },
  uuid: {
    summary: "Generate random UUID version 4 identifiers with the browser cryptographic random source.",
    introduction: "The UUID generator creates a new version 4 UUID in the current browser. UUIDs are useful as identifiers when coordination through one central sequence is inconvenient.",
    useCases: ["Create identifiers for test fixtures or local records.", "Generate a request or correlation ID during development."],
    steps: ["Open the tool to create an initial UUID.", "Select Generate to replace it with another UUID v4.", "Copy the value where an identifier is needed."],
    example: { title: "UUID v4 shape", description: "A generated value follows the 8-4-4-4-12 hexadecimal layout, with version and variant bits set by the browser." },
    principles: ["The implementation calls crypto.randomUUID(), which produces a random UUID version 4 using a cryptographically secure random source provided by the browser."],
    limitations: ["A UUID is an identifier, not a secret, password, access token, or proof that a record exists.", "Random UUID collision probability is extremely low but not a mathematical guarantee of global uniqueness."],
    faqs: [
      { question: "Which UUID version is generated?", answer: "The tool generates UUID version 4 values." },
      { question: "Can I derive a timestamp from it?", answer: "No. Version 4 UUIDs are random and do not encode creation time." },
    ],
    references: [{ label: "RFC 9562 — UUIDs", url: "https://www.rfc-editor.org/info/rfc9562/" }],
    aliases: ["guid generator", "uuid v4", "random id", "unique identifier"],
    keywords: ["UUID", "GUID", "version 4", "random", "identifier", "crypto"],
    reviewedAt,
  },
  timestamp: {
    summary: "Convert Unix-style seconds or milliseconds to ISO UTC text, and local date-time input to both units.",
    introduction: "The timestamp converter supports two directions. Choose seconds or milliseconds explicitly for numeric input and receive an ISO 8601 UTC string; a browser local date-time input is converted to Unix seconds and milliseconds.",
    useCases: ["Inspect an API timestamp as a readable UTC instant.", "Create seconds and milliseconds for a selected local date and time."],
    steps: ["Enter an integer timestamp and select seconds or milliseconds, or choose a local date and time.", "Review the ISO UTC result or the seconds/milliseconds pair.", "Use the swap action to transfer a valid value between the two sections."],
    example: { title: "Unix epoch sample", description: "1704067200 seconds converts to 2024-01-01T00:00:00.000Z." },
    principles: ["JavaScript Date stores milliseconds since the Unix epoch. ISO output is produced in UTC with toISOString; datetime-local input is interpreted in the browser’s local timezone."],
    limitations: ["Fractional and out-of-range timestamps are rejected; the selected unit is never inferred from digit count.", "A datetime-local field has no timezone suffix and therefore uses the current browser timezone shown beside the field.", "Leap seconds are not represented by JavaScript Date."],
    faqs: [
      { question: "How are seconds and milliseconds distinguished?", answer: "You select the unit explicitly, so historic and far-future values are not guessed by digit count." },
      { question: "Why does the ISO result end in Z?", answer: "Z denotes UTC. The tool converts the instant to a UTC ISO string for display." },
      { question: "Which timezone is used for date-time input?", answer: "The browser interprets datetime-local values in its current local timezone." },
    ],
    references: [DATE_REFERENCE],
    aliases: ["unix timestamp", "epoch converter", "seconds to date", "milliseconds to date"],
    keywords: ["timestamp", "Unix", "epoch", "ISO 8601", "UTC", "timezone", "milliseconds"],
    reviewedAt,
  },
  case: {
    summary: "Convert text to uppercase, lowercase, title-style words, or a basic camelCase form.",
    introduction: "The text case converter applies browser Unicode-aware case operations and simple word transformations. It is useful for editing labels, headings, and identifiers without sending text away from the browser.",
    useCases: ["Normalize a heading to uppercase or lowercase.", "Turn words separated by spaces, underscores, or hyphens into a basic camelCase identifier."],
    steps: ["Enter or paste text.", "Choose upper, lower, title, or camel mode.", "Review and copy the transformed text."],
    example: { title: "Basic camel case", description: "Lite tools_example becomes liteToolsExample." },
    principles: ["Upper and lower modes use locale-aware browser casing. Title mode capitalizes matched Unicode words; camel mode removes spaces, underscores, and hyphens before uppercasing the following character."],
    limitations: ["Title casing is rule-based and does not apply language-specific headline style exceptions.", "Camel mode is a basic separator transformation and does not tokenize every punctuation or acronym convention.", "Some Unicode casing operations can change string length."],
    faqs: [
      { question: "Does title mode understand editorial style guides?", answer: "No. It capitalizes word starts and does not keep language-specific minor words lowercase." },
      { question: "Will camel mode preserve acronyms?", answer: "Not reliably. It applies simple casing rules rather than an acronym dictionary." },
    ],
    references: [{ label: "Unicode Standard", url: "https://www.unicode.org/standard/standard.html" }],
    aliases: ["uppercase converter", "lowercase converter", "title case", "camel case"],
    keywords: ["text case", "uppercase", "lowercase", "title", "camelCase", "Unicode"],
    reviewedAt,
  },
  text: {
    summary: "Count user-perceived Unicode grapheme clusters, whitespace-separated word groups, and text lines locally.",
    introduction: "The word counter reports characters, words, and lines as defined by the current implementation. It is intended for quick text inspection rather than language-aware publishing counts.",
    useCases: ["Check the approximate length of a short draft.", "Count lines in pasted notes or a small text block."],
    steps: ["Paste or type text in the input area.", "Read the character, word, and line totals as they update.", "Copy the three totals if a portable summary is needed."],
    example: { title: "Mixed-language text", description: "For one two followed by a newline and 三, the tool reports 9 characters, 3 whitespace-separated words, and 2 lines." },
    principles: ["Characters use Intl.Segmenter grapheme boundaries when available, so combining sequences and joined emoji count as one visible character. Words are non-empty groups separated by whitespace. Lines are separated by CRLF, CR, or LF; empty input has zero lines."],
    limitations: ["Chinese text without spaces is counted as one word group rather than segmented into individual words.", "The fallback used by older browsers approximates common combining and emoji sequences and can differ from full Unicode grapheme segmentation.", "The tool does not count pages, sentences, reading time, or byte length."],
    faqs: [
      { question: "Are spaces counted as characters?", answer: "Yes. Character counting includes whitespace grapheme clusters." },
      { question: "How are Chinese words counted?", answer: "Only whitespace boundaries are used, so an unspaced Chinese sentence is one word group." },
      { question: "Does a trailing newline add a line?", answer: "Splitting by line breaks can produce an additional empty final line when the input ends with a newline." },
    ],
    references: [{ label: "Unicode Standard", url: "https://www.unicode.org/standard/standard.html" }],
    aliases: ["character counter", "word count", "line counter", "text statistics"],
    keywords: ["words", "characters", "lines", "whitespace", "Unicode", "count"],
    reviewedAt,
  },
  color: {
    summary: "Convert HEX to RGB, or RGB channel values to HEX and HSL.",
    introduction: "The color converter supports three- or six-digit HEX input and numeric red, green, and blue channels. It produces CSS-style RGB, HEX, and HSL representations.",
    useCases: ["Inspect the RGB channels of a HEX design color.", "Create a HEX and HSL representation from RGB values."],
    steps: ["Enter a HEX value or RGB channels from 0 to 255.", "Review the corresponding color notation.", "Copy the generated text."],
    example: { title: "Brand green", description: "#187b69 converts to rgb(24, 123, 105); those RGB channels produce #187b69 and an HSL value." },
    principles: ["HEX stores each RGB channel as two hexadecimal digits. HSL is derived from normalized RGB extrema and rounded to integer hue, saturation, and lightness values."],
    limitations: ["RGB channels are rounded to the nearest integer for HEX output.", "The tool does not convert alpha, wide-gamut color spaces, profiles, LAB, LCH, or color appearance.", "Displayed HSL rounding can prevent an exact round trip."],
    faqs: [
      { question: "Does three-digit HEX work?", answer: "Yes. Each digit is doubled, so #abc is interpreted as #aabbcc." },
      { question: "Are RGB values clamped?", answer: "No. Values outside 0–255 are rejected instead of clamped." },
    ],
    references: [{ label: "CSS Color Module Level 4", url: "https://www.w3.org/TR/css-color-4/" }],
    aliases: ["hex to rgb", "rgb to hex", "rgb to hsl", "css color converter"],
    keywords: ["color", "HEX", "RGB", "HSL", "CSS", "palette"],
    reviewedAt,
  },
  percentage: {
    summary: "Calculate a selected percentage of a base value.",
    introduction: "The percentage calculator answers the form “what is P percent of V?” with a direct multiplication. It accepts finite positive or negative numbers.",
    useCases: ["Calculate a tax or tip amount before adding it to a total.", "Find a proportional quantity such as 12.5% of a measurement."],
    steps: ["Enter the percentage.", "Enter the base value.", "Review and copy the calculated amount."],
    example: { title: "Ten percent", description: "10% of 250 is 25." },
    principles: ["The implemented formula is result = percentage ÷ 100 × base value."],
    limitations: ["This tool does not calculate percentage change, reverse percentages, margins, or a final total automatically.", "Negative and values above 100% are allowed because they can be meaningful in general arithmetic."],
    faqs: [
      { question: "Does the result include the original value?", answer: "No. It returns only the percentage amount." },
      { question: "Can the percentage exceed 100?", answer: "Yes. The implementation accepts any finite percentage." },
    ],
    references: [NIST_PERCENT_REFERENCE],
    aliases: ["percent of number", "percentage of value", "percent calculator", "calculate percent"],
    keywords: ["percentage", "percent", "ratio", "base value", "calculation"],
    reviewedAt,
  },
  discount: {
    summary: "Calculate a final price and amount saved from an original price and discount rate.",
    introduction: "The discount calculator applies one percentage reduction to a non-negative original price. It displays both the reduced price and the saving.",
    useCases: ["Check a sale price before purchasing.", "Compare the saving produced by a listed percentage discount."],
    steps: ["Enter the original price.", "Enter a discount rate from 0 to 100.", "Review the final price and saving."],
    example: { title: "Fifteen percent off", description: "An original price of 100 with a 15% discount returns a final price of 85 and a saving of 15." },
    principles: ["Final price = original price × (1 − discount ÷ 100); saving = original price × discount ÷ 100."],
    limitations: ["The calculator does not add tax, shipping, fees, coupons, tiered discounts, or currency conversion.", "Results are numeric references and not financial advice or a retailer quote."],
    faqs: [
      { question: "Can the discount exceed 100%?", answer: "No. Rates below 0 or above 100 are rejected." },
      { question: "Does it know my currency?", answer: "No. Values are unitless, so use the same currency for the original price and result." },
    ],
    references: [NIST_PERCENT_REFERENCE],
    aliases: ["sale price calculator", "percent off", "discount price", "savings calculator"],
    keywords: ["discount", "sale", "price", "saving", "percentage"],
    reviewedAt,
  },
  bmi: {
    summary: "Calculate adult body mass index from kilograms and centimetres as a general reference.",
    introduction: "The BMI calculator divides weight in kilograms by height in metres squared. BMI is a population screening measure and does not directly measure body composition or diagnose health.",
    useCases: ["Calculate a general adult BMI reference from metric measurements.", "Check the arithmetic behind a BMI value discussed with a qualified professional."],
    steps: ["Enter weight in kilograms.", "Enter height in centimetres.", "Review the BMI number together with the health disclaimer."],
    example: { title: "Metric BMI", description: "A weight of 70 kg and height of 175 cm produces a BMI of about 22.9." },
    principles: ["BMI = weight (kg) ÷ height² (m²). The implementation converts centimetres to metres before squaring."],
    limitations: ["The displayed adult ranges are general screening labels, not a medical diagnosis.", "BMI does not distinguish muscle, fat, bone, age, sex, ethnicity, pregnancy, or individual clinical circumstances.", "Children require age- and sex-specific assessment rather than these adult ranges."],
    faqs: [
      { question: "Do the displayed BMI ranges provide a diagnosis?", answer: "No. They are general adult screening labels and do not provide a diagnosis." },
      { question: "Can children use the same interpretation?", answer: "No. Child and adolescent assessment requires age- and sex-specific growth references." },
      { question: "Why are centimetres converted?", answer: "The BMI formula uses height in metres, so centimetres are divided by 100 first." },
    ],
    references: [{ label: "WHO — Obesity and overweight", url: "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight" }],
    aliases: ["body mass index", "BMI checker", "kg cm BMI", "health calculator"],
    keywords: ["BMI", "body mass index", "weight", "height", "health", "not diagnosis"],
    reviewedAt,
  },
  compound: {
    summary: "Estimate compound growth from principal, annual rate, years, and a selected compounding frequency.",
    introduction: "The compound interest calculator estimates how a principal grows at a selected number of compounding periods per year. It returns the final amount and the difference from the principal.",
    useCases: ["Explore a simplified savings-growth scenario.", "Compare how a nominal annual rate compounds over a selected number of years."],
    steps: ["Enter the principal.", "Enter the annual percentage rate, number of years, and compounding periods per year.", "Review the estimated amount and interest."],
    example: { title: "Monthly compounding", description: "A principal of 1,000 at 12% per year for 1 year with monthly compounding produces about 1,126.83." },
    principles: ["The implemented formula is A = P(1 + r/n)^(nt): the annual percentage rate is divided by 100 and n is the selected integer number of periods per year."],
    limitations: ["The interface accepts 1 to 365 compounding periods per year and does not accept deposits, withdrawals, fees, taxes, inflation, changing rates, or day-count conventions.", "The result is a mathematical estimate, not financial advice or a promised return.", "Inputs that make the periodic growth factor non-positive or the result non-finite are rejected."],
    faqs: [
      { question: "Can I choose annual, monthly, or daily compounding?", answer: "Yes. Enter 1, 12, or up to 365 compounding periods per year." },
      { question: "Are regular contributions included?", answer: "No. Only one initial principal is included." },
      { question: "Is the displayed interest simple interest?", answer: "No. It is the final compounded amount minus the principal." },
    ],
    references: [{ label: "Investor.gov Compound Interest Calculator", url: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" }],
    aliases: ["compound interest", "monthly compounding", "investment growth", "interest calculator"],
    keywords: ["compound", "principal", "annual rate", "years", "monthly", "interest"],
    reviewedAt,
  },
  datecalc: {
    summary: "Calculate the absolute elapsed day difference between two browser date inputs.",
    introduction: "The date interval calculator validates two Gregorian calendar dates and returns their absolute elapsed calendar-day difference.",
    useCases: ["Check the elapsed-day gap between two ordinary dates.", "Compare two deadlines without manually counting calendar squares."],
    steps: ["Select the start date.", "Select the end date.", "Review the absolute number of elapsed days."],
    example: { title: "January interval", description: "From 2024-01-01 to 2024-01-31 the tool returns 30 days." },
    principles: ["Each strict YYYY-MM-DD input is constructed as a UTC Gregorian calendar date, then the absolute day-boundary difference is calculated. This avoids local timezone and daylight-saving shifts."],
    limitations: ["The count is an elapsed difference and is not inclusive of both endpoint dates; January 1 to January 31 returns 30, not 31.", "Invalid rollover dates such as February 30 are rejected.", "Business days, holidays, months, and calendar schedules are not calculated."],
    faqs: [
      { question: "Does the order of the dates matter?", answer: "No. The absolute difference is used." },
      { question: "Are both start and end dates counted?", answer: "No. The result is the elapsed gap between them." },
      { question: "Does it exclude weekends?", answer: "No. Every elapsed day is treated equally." },
    ],
    references: [DATE_REFERENCE],
    aliases: ["days between dates", "date difference", "day interval", "elapsed days"],
    keywords: ["date", "interval", "difference", "days", "elapsed", "timezone"],
    reviewedAt,
  },
  qr: {
    summary: "Generate a styled QR Code PNG with controlled shapes and an optional local raster logo.",
    introduction: "The QR Code generator encodes supplied text entirely in the browser. You can choose size, colors, error correction, controlled module and finder presets, and an optional local PNG, JPEG, or WebP logo before downloading the composed PNG.",
    useCases: ["Create a high-contrast QR Code for a public web address.", "Add a small local brand mark to a short code after testing the final image with intended scanners."],
    steps: ["Enter the exact text or URL to encode.", "Choose high-contrast colors and a controlled shape preset; optionally select a local raster logo.", "Scan-test the current preview, then download the PNG if it works with the intended readers."],
    example: { title: "Local logo", description: "Selecting a medium local PNG logo forces H error correction and places the image within a solid center backing without changing the four-module quiet zone." },
    principles: ["The browser-side qrcode library creates the encoded module matrix. The local renderer preserves a four-module quiet zone, redraws the three finder patterns, and composites an optional logo at 12%, 16%, or 20% of the symbol width."],
    limitations: ["This interface rejects empty input and content over 1,200 UTF-8 bytes as a conservative reliability guard; non-ASCII characters can use multiple bytes and practical capacity also depends on QR encoding mode.", "A logo forces H error correction, but error correction cannot guarantee compatibility. Scanner behavior depends on content density, contrast, output size, printing, camera, and reader software, so always test the final artifact.", "Logos accept local PNG, JPEG, or WebP files up to 2 MB and 2048 × 2048 pixels; SVG and remote image URLs are not accepted.", "A QR Code stores the supplied content; it does not verify that a URL is safe or keep the content secret."],
    faqs: [
      { question: "Is the QR content uploaded?", answer: "No. The application generates the image in the current browser." },
      { question: "Why can a long QR Code be hard to scan?", answer: "More data requires a denser symbol. At a fixed image size, smaller modules are harder for some cameras and printers to resolve." },
      { question: "Which colors work best?", answer: "A dark foreground on a light, high-contrast background is the safest general choice." },
    ],
    references: [
      { label: "DENSO WAVE — QR Code versions and capacity", url: "https://www.qrcode.com/en/about/version.html" },
      { label: "DENSO WAVE — QR Code standardization", url: "https://www.qrcode.com/en/about/standards.html" },
    ],
    aliases: ["qr generator", "qr code maker", "text to qr", "url qr"],
    keywords: ["QR Code", "PNG", "scanner", "capacity", "contrast", "local"],
    reviewedAt,
  },
  irr: {
    summary: "Solve fixed-period internal rate of return and convert the periodic rate to an annualized equivalent.",
    introduction: "The IRR calculator finds rates above −100% where the net present value of 2 to 200 equally spaced cash flows is zero. It reports a periodic result, an annualized result for monthly, quarterly, or yearly periods, and explicit diagnostics for missing sign changes, no root, multiple roots, or failed convergence.",
    useCases: ["Check the fixed-period return implied by an initial outflow and later inflows.", "Compare the mathematical annualized equivalent of monthly or quarterly periodic IRR."],
    steps: ["Enter each cash flow in chronological period order, including period 0.", "Choose whether one period means a month, quarter, or year.", "Review the single result or the diagnostic explaining why one unambiguous IRR is unavailable."],
    example: { title: "One-period reference", description: "Cash flows of −1,000 and 1,100 produce a periodic IRR of 10%. If that period is yearly, the annualized IRR is also 10%." },
    principles: ["IRR solves Σ(CFₜ/(1+r)ᵗ)=0 for r > −1. The solver scans a bounded transformed rate domain for candidate brackets and uses bounded bisection rather than an unprotected Newton iteration.", "Annualized IRR is (1 + periodic IRR) raised to 12, 4, or 1 periods per year, minus 1."],
    limitations: ["Cash flows must be equally spaced; actual dates and XIRR are not supported.", "Non-conventional cash flows can have multiple IRRs. A bounded scan can identify multiple candidate roots but cannot prove global uniqueness for every possible sequence.", "IRR is a mathematical result, not a guaranteed return or investment advice."],
    faqs: [
      { question: "Does this calculator support XIRR?", answer: "No. It accepts period numbers only and assumes equal spacing." },
      { question: "Why can one cash-flow sequence have multiple IRRs?", answer: "When cash-flow signs change more than once, the NPV equation can cross zero at more than one rate." },
      { question: "What does no root mean?", answer: "No stable zero crossing was found within the documented bounded search domain; the tool does not fabricate a rate." },
    ],
    references: [{ label: "NumPy Financial — IRR definition", url: "https://numpy.org/numpy-financial/latest/irr.html" }],
    aliases: ["internal rate of return", "periodic IRR", "annualized IRR", "investment return"],
    keywords: ["IRR", "cash flow", "NPV", "periodic", "annualized", "multiple roots"],
    reviewedAt: "2026-07-30",
  },
  cheque: {
    summary: "Convert a non-negative decimal amount to English cheque words and Chinese financial numerals.",
    introduction: "The cheque amount converter parses the amount as exact text rather than a floating-point number. It can keep the default currency-neutral wording or add an approved HKD, USD, RMB, or SGD label, choose English letter case, and switch between Traditional and Simplified Chinese financial numerals.",
    useCases: ["Prepare a draft English amount line before completing a paper cheque.", "Check the zero placement around 萬, 億, 兆, 万, 亿, and 兆 in Chinese financial numerals."],
    steps: ["Enter an amount from 0 through 999,999,999,999,999.99 with up to two decimal places.", "Choose whether to add a currency label, select English case, and select Traditional or Simplified Chinese financial wording.", "Copy the required line and verify it against the receiving bank's rules."],
    example: { title: "Optional currency label", description: "21.05 can stay TWENTY-ONE AND 05/100 ONLY, or become HONG KONG DOLLARS TWENTY-ONE AND CENTS FIVE ONLY with HKD selected." },
    principles: ["The parser validates optional three-digit comma grouping and stores the integer and two fractional digits exactly. It never rounds a third decimal digit.", "English tens from 21 to 99 use hyphens. Chinese output uses financial digits and suppresses redundant zeros across four-digit sections. Valid plain numbers are grouped on blur for readability."],
    limitations: ["The default output is currency-neutral; currency labels are optional common wording aids, not bank-specific rules.", "Negative values, scientific notation, incorrectly grouped commas, more than two decimal places, and amounts above the documented maximum are rejected.", "Bank and regional writing rules vary, so the output is a writing aid and must be checked against actual requirements. On paper, fill the blank space after the written amount to reduce tampering risk."],
    faqs: [
      { question: "Does the result have to specify dollars, yuan, or another currency?", answer: "No. The default is currency-neutral, and the currency selector is optional." },
      { question: "Will a third decimal digit be rounded?", answer: "No. Inputs with more than two decimal places are rejected." },
      { question: "Can I switch Chinese financial numerals?", answer: "Yes. The Chinese result can use either Traditional or Simplified financial numerals." },
      { question: "Should I draw a line after the amount on paper?", answer: "Many cheque-writing practices fill the remaining blank space after the written amount to reduce tampering risk. Check your bank's exact requirement." },
    ],
    references: [{ label: "Hong Kong Monetary Authority — Smart tips on using cheques", url: "https://www.hkma.gov.hk/eng/smart-consumers/smart-tips-on-using-cheques/" }],
    aliases: ["check amount", "number to words", "financial numerals", "cheque writing", "HKD cheque", "RMB uppercase amount"],
    keywords: ["cheque", "check", "amount", "English words", "financial numerals", "Traditional Chinese", "Simplified Chinese", "currency label"],
    reviewedAt: "2026-07-30",
  },
  password: {
    summary: "Generate one or more constrained passwords with the browser cryptographic random source.",
    introduction: "The password generator supports length, batch size, character categories, per-category minimums, custom printable ASCII symbols, and optional exclusion of I, l, 1, O, 0, o, and |. Generated values exist only in the current page state.",
    useCases: ["Generate a password that must contain a specified minimum from several character classes.", "Create a local batch without sending candidates to a password service."],
    steps: ["Choose a length from 8 to 128 and a batch size from 1 to 50.", "Enable character categories, set their minimums, and review the allowed symbol set.", "Generate, then copy one result or the complete batch through an explicit action."],
    example: { title: "Constrained 16-character password", description: "With all four categories enabled and each minimum set to 1, every generated 16-character result contains at least one uppercase letter, lowercase letter, number, and allowed symbol." },
    principles: ["Production generation uses crypto.getRandomValues(). Rejection sampling avoids modulo bias, required characters are selected first, and the final characters are shuffled with the same secure source.", "The relative strength label uses configured length and effective character-pool size; it does not predict a certain cracking time."],
    limitations: ["The tool does not generate passphrases, query breach databases, save passwords, or provide an absolute security guarantee.", "Custom symbols accept visible ASCII punctuation only, and a constrained result space can be too small for a unique batch.", "Clipboard writes occur only after a copy action; clipboard contents remain subject to the browser and operating system."],
    faqs: [
      { question: "Are passwords stored or added to the URL?", answer: "No. Configuration changes clear old results, and refresh does not restore generated passwords." },
      { question: "Does excluding confusing characters make a password stronger?", answer: "It can improve readability but reduces the character pool, so length and other rules still matter." },
      { question: "Does the strength label guarantee safety?", answer: "No. It is a relative configuration indicator, not a promise or cracking-time estimate." },
    ],
    references: [{ label: "NIST SP 800-63B — Authentication and authenticator management", url: "https://pages.nist.gov/800-63-4/sp800-63b.html" }],
    aliases: ["secure password", "random password", "password maker", "credential generator"],
    keywords: ["password", "crypto", "random", "minimum characters", "symbols", "batch"],
    reviewedAt: "2026-07-30",
  },
};
