import { TOOL_CONTENT_EN } from "./tool-content.en.js";

const localize = (id, content) => ({
  ...content,
  references: TOOL_CONTENT_EN[id].references,
  reviewedAt: TOOL_CONTENT_EN[id].reviewedAt,
});

export const TOOL_CONTENT_ZH_CN = {
  length: localize("length", {
    summary: "以米为共同基准，转换常见公制、英制和美制长度单位。",
    introduction: "长度转换支持米、千米、厘米、毫米、英寸、英尺、码和英里，适合处理图纸、行程或商品规格中单位不一致的情况。",
    useCases: ["比较以米和英尺标注的房间或家具尺寸。", "在千米和英里之间换算道路距离。"],
    steps: ["输入有限的长度数值。", "选择输入单位和目标单位。", "检查结果，按需复制。"],
    example: { title: "米转英尺", description: "输入 1 米并选择英尺，结果约为 3.280839895 英尺。" },
    principles: ["每个单位都以米表示固定换算因子；输入值先乘来源因子，再除以目标因子。"],
    limitations: ["显示结果最多保留 10 位小数，精密工作应保留原始测量值。", "本工具只转换长度，不会把长度因子自动平方或立方来转换面积、体积。"],
    faqs: [
      { question: "1 米等于多少英尺？", answer: "工具采用国际英尺的精确定义 0.3048 米，因此 1 米约为 3.280839895 英尺。" },
      { question: "可以输入负数吗？", answer: "可以输入任何有限数值，但负长度在多数实际场景中没有物理意义。" },
    ],
    aliases: ["距离转换", "米转英尺", "千米转英里", "m 转 ft"],
    keywords: ["长度", "距离", "米", "英尺", "英里", "码"],
  }),
  weight: localize("weight", {
    summary: "通过千克基准转换千克、克、毫克、磅、盎司和公吨。",
    introduction: "重量转换适合日常质量单位换算。虽然日常常称为“重量”，这里使用固定因子转换的是质量。",
    useCases: ["把包裹质量从千克换算为磅。", "在克和盎司之间转换配方用量。"],
    steps: ["输入有限的质量数值。", "选择来源单位和目标单位。", "检查并复制结果。"],
    example: { title: "千克转磅", description: "输入 1 千克，结果约为 2.204622622 磅。" },
    principles: ["所有数值都通过千克换算；国际常衡磅按 0.45359237 千克计算。"],
    limitations: ["工具不考虑当地重力，因此不计算以牛顿表示的力。", "显示值可能经过舍入，商业称重还可能受计量法规约束。"],
    faqs: [
      { question: "“吨”指哪一种吨？", answer: "指 1,000 千克的公吨，不是美制短吨或英制长吨。" },
      { question: "磅和盎司采用常衡制吗？", answer: "是，当前因子采用常见的国际常衡磅和盎司。" },
    ],
    aliases: ["质量转换", "千克转磅", "克转盎司", "kg 转 lb"],
    keywords: ["重量", "质量", "千克", "磅", "盎司", "公吨"],
  }),
  temperature: localize("temperature", {
    summary: "使用标准偏移公式转换摄氏、华氏和开尔文温度。",
    introduction: "摄氏和华氏的零点不同，温度换算不能只乘一个比例。本工具通过摄氏度在摄氏、华氏和开尔文之间转换。",
    useCases: ["在摄氏和华氏之间换算天气温度。", "把实验温度从摄氏转换为开尔文。"],
    steps: ["输入有限温度。", "选择当前温标和目标温标。", "检查转换结果。"],
    example: { title: "水的冰点", description: "输入 0 °C，转换为 32 °F 或 273.15 K。" },
    principles: ["华氏公式为 °F = °C × 9/5 + 32；开尔文公式为 K = °C + 273.15。"],
    limitations: ["低于绝对零度（−273.15 °C、−459.67 °F 或 0 K）的输入会被拒绝；边界值本身有效。", "不处理测量不确定度或材料随温度变化的性质。"],
    faqs: [
      { question: "开尔文为什么没有度数符号？", answer: "SI 单位名称是开尔文，符号为 K，不使用度数符号。" },
      { question: "摄氏和华氏何时数值相同？", answer: "两者在 −40 时数值相同。" },
    ],
    aliases: ["摄氏转华氏", "华氏转摄氏", "开尔文转换", "温标转换"],
    keywords: ["温度", "摄氏", "华氏", "开尔文", "绝对零度"],
  }),
  area: localize("area", {
    summary: "通过平方米转换公制平方单位、公顷、英亩和平方英尺。",
    introduction: "面积转换覆盖土地、房间和图纸常用单位，所有选项都作为面积单位并通过平方米换算。",
    useCases: ["比较英亩和公顷表示的土地面积。", "把房间面积从平方米转换为平方英尺。"],
    steps: ["输入有限面积。", "选择输入和目标面积单位。", "检查并复制结果。"],
    example: { title: "平方米转平方英尺", description: "1 平方米约为 10.763910417 平方英尺。" },
    principles: ["面积因子来自长度关系的平方，例如 1 平方英尺等于 0.09290304 平方米。"],
    limitations: ["不会根据边长推算不规则图形面积。", "测绘和法定土地记录可能使用当地定义或舍入规则。"],
    faqs: [
      { question: "1 公顷是多少平方米？", answer: "1 公顷等于 10,000 平方米。" },
      { question: "英亩是否必须是正方形？", answer: "不是。英亩是 4,046.8564224 平方米的面积，可以有不同形状。" },
    ],
    aliases: ["土地面积转换", "平方米转平方英尺", "英亩转公顷", "平方单位转换"],
    keywords: ["面积", "平方米", "平方英尺", "英亩", "公顷"],
  }),
  volume: localize("volume", {
    summary: "转换升、毫升、立方米及常见美制液体体积单位。",
    introduction: "体积转换把公制单位与美制加仑、夸脱、品脱和杯组合在一起，所有换算都以升为共同基准。",
    useCases: ["把容器容量从升换算为美制加仑。", "在毫升和美制杯之间转换烹饪用量。"],
    steps: ["输入有限体积。", "选择来源和目标单位。", "读取并复制结果。"],
    example: { title: "升转美制加仑", description: "1 升约为 0.264172052 美制加仑。" },
    principles: ["1 立方米等于 1,000 升；1 美制液体加仑按 3.785411784 升计算。"],
    limitations: ["加仑、夸脱、品脱和杯均为美制液体单位，不是英制单位。", "工具只转换体积，不能在不知道密度时转换为质量。"],
    faqs: [
      { question: "这里使用哪一种加仑？", answer: "使用美制液体加仑，未提供容量不同的英制加仑。" },
      { question: "可以把升直接换成千克吗？", answer: "不可以，必须知道物质密度，而本工具不要求该数据。" },
    ],
    aliases: ["升转换", "升转加仑", "毫升转杯", "液体体积"],
    keywords: ["体积", "升", "毫升", "加仑", "杯", "立方米"],
  }),
  speed: localize("speed", {
    summary: "转换米／秒、公里／小时、英里／小时、节和英尺／秒。",
    introduction: "速度转换适用于道路、航海、航空和科学场景，所有单位都通过米／秒换算。",
    useCases: ["比较公里／小时和英里／小时的行车速度。", "把以节表示的航速换算为米／秒。"],
    steps: ["输入有限速度。", "选择当前单位和目标单位。", "检查转换结果。"],
    example: { title: "公里／小时转英里／小时", description: "100 km/h 约为 62.137119224 mph。" },
    principles: ["速度是距离除以时间，固定因子先把每个选项表示为米／秒。"],
    limitations: ["只转换速度大小，不包含方向、加速度、风或水流。", "显示舍入不适合导航或安全关键计算。"],
    faqs: [
      { question: "“节”是什么？", answer: "1 节是每小时 1 海里，本工具按约 0.5144444444 米／秒计算。" },
      { question: "mph 是否指英里／小时？", answer: "是，使用国际英里和 3,600 秒的小时。" },
    ],
    aliases: ["速度单位转换", "公里时转英里时", "kmh 转 mph", "节转换"],
    keywords: ["速度", "米每秒", "公里每小时", "英里每小时", "节"],
  }),
  time: localize("time", {
    summary: "用固定秒数因子转换毫秒至周的持续时间。",
    introduction: "时间转换处理经过时长而不是日历日期，毫秒、秒、分钟、小时、天和周都通过秒换算。",
    useCases: ["把程序超时从毫秒转换为秒。", "把项目时长从小时转换为天或周。"],
    steps: ["输入有限时长。", "选择来源和目标时长单位。", "检查结果。"],
    example: { title: "小时转分钟", description: "1 小时等于 60 分钟。" },
    principles: ["采用 1 分钟 = 60 秒、1 小时 = 3,600 秒、1 天 = 86,400 秒、1 周 = 604,800 秒。"],
    limitations: ["天和周都是固定时长，不考虑夏令时、闰秒、月份和日历规则。", "这不是时区或排期工具。"],
    faqs: [
      { question: "每一天都按 24 小时吗？", answer: "是，本转换器固定按 86,400 秒计算一天。" },
      { question: "可以转换月份或年份吗？", answer: "不可以，因为它们的日历长度并不固定。" },
    ],
    aliases: ["时长转换", "小时转分钟", "秒转毫秒", "天转周"],
    keywords: ["时间", "时长", "毫秒", "秒", "小时", "天", "周"],
  }),
  storage: localize("storage", {
    summary: "明确区分 SI 十进制 kB–PB 与 IEC 二进制 KiB–PiB 后转换字节容量。",
    introduction: "数据存储转换将十进制存储标签和二进制容量标签分开处理，不再把 KB 与 KiB 视为相同单位。",
    useCases: ["比较硬盘厂商的十进制容量与操作系统的二进制显示。", "在 SI 与 IEC 单位之间换算同一个字节数。"],
    steps: ["输入有限容量。", "明确选择当前使用的十进制或二进制单位。", "选择目标单位并查看结果。"],
    example: { title: "GB 与 GiB", description: "1 GB 等于 1,000 MB；1 GiB 等于 1,024 MiB；1 MiB 等于 1.048576 MB。" },
    principles: ["SI 十进制单位按 1,000 进位：1 kB = 1,000 B。IEC 二进制单位按 1,024 进位：1 KiB = 1,024 B。"],
    limitations: ["结果超过 JavaScript 安全整数范围时会被拒绝，避免把可能失真的字节数显示为精确值。", "不读取文件、压缩率、文件系统开销或可用空间。"],
    faqs: [
      { question: "GB 与 GiB 有什么区别？", answer: "GB 是十进制单位，等于 1,000,000,000 B；GiB 是二进制单位，等于 1,073,741,824 B。" },
      { question: "为什么硬盘容量与系统显示可能不同？", answer: "硬盘厂商通常使用十进制单位，部分系统以二进制数量显示，因此同一字节数的标签数值不同。" },
    ],
    aliases: ["文件大小转换", "GB 转 MB", "GiB 转 MiB", "字节转换"],
    keywords: ["存储", "字节", "KB", "KiB", "GB", "GiB", "1000", "1024"],
  }),
  json: localize("json", {
    summary: "使用浏览器 JSON 解析器在本地格式化、压缩和校验 JSON。",
    introduction: "JSON 工具会解析输入以校验语法；格式化模式使用两空格缩进，压缩模式移除非必要空白。格式化和压缩改变展示形式，校验判断文本是否符合 JSON 语法。",
    useCases: ["把紧凑的 API 响应整理成易读结构。", "在保存前压缩有效的配置片段。"],
    steps: ["粘贴或输入 JSON。", "选择“格式化”或“压缩”。", "解析成功后检查并复制结果；失败时查看本地错误信息。"],
    example: { title: "格式化对象", description: "输入 {\"active\":true,\"count\":2} 后，格式化模式会输出两空格缩进的多行对象。" },
    principles: ["实现用 JSON.parse 校验，再用 JSON.stringify 输出。空白不影响 JSON 值的语义。"],
    limitations: ["注释、尾随逗号、未加引号的键、NaN 和 Infinity 都不是有效 JSON。", "JavaScript 数值精度有限，超大整数可能失真。"],
    faqs: [
      { question: "格式化会改变数据吗？", answer: "对有效 JSON，它主要改变空白和缩进；JavaScript 数值精度限制仍然存在。" },
      { question: "压缩是否等于加密？", answer: "不是。压缩模式只移除非必要空白，文本仍可读取。" },
      { question: "JSON 会上传吗？", answer: "不会，解析和输出都在当前浏览器进行。" },
    ],
    aliases: ["JSON 格式化", "JSON 校验", "JSON 压缩", "JSON 美化"],
    keywords: ["JSON", "格式化", "压缩", "校验", "解析器", "开发工具"],
  }),
  base64: localize("base64", {
    summary: "把 Unicode 文本编码为标准 Base64，或解码回文本。",
    introduction: "Base64 工具先把文本转换为 UTF-8 字节，再进行标准 Base64 编码；解码时执行相反过程。Base64 用可打印字符表示字节，不是安全机制。",
    useCases: ["把短 Unicode 文本编码后放入只接受文本的字段。", "解码标准 Base64 字符串以查看其 UTF-8 文本。"],
    steps: ["编码时输入文本，解码时输入 Base64。", "选择编码或解码方向。", "检查并复制本地结果。"],
    example: { title: "Unicode 文本", description: "编码 Hello 世界时，字符先变成 UTF-8 字节，再生成带填充的标准 Base64。" },
    principles: ["使用 TextEncoder 和 TextDecoder 处理 UTF-8，并使用浏览器 btoa/atob 的标准 Base64 字母表与填充。"],
    limitations: ["Base64 是编码而不是加密，任何人都可以解码内容。", "当前只接受带正确填充的标准 Base64，不是 URL 和文件名安全的 Base64url。", "解码后的字节必须是有效 UTF-8 文本；任意二进制数据会被拒绝。"],
    faqs: [
      { question: "为什么输出更长？", answer: "Base64 通常用 4 个字符表示 3 个输入字节，并可能加入填充。" },
      { question: "可以保护密码吗？", answer: "不可以，Base64 没有保密能力。" },
      { question: "支持中文吗？", answer: "支持，文本会先转换为 UTF-8 字节。" },
    ],
    aliases: ["Base64 编码", "Base64 解码", "b64", "Unicode Base64"],
    keywords: ["Base64", "编码", "解码", "UTF-8", "文本", "非加密"],
  }),
  url: localize("url", {
    summary: "按 JavaScript 百分号规则编码或解码一个 URL 组件。",
    introduction: "URL 编解码把整段输入当作一个 URL 组件处理，不会把完整 URL 拆分为协议、主机、路径和查询参数。",
    useCases: ["编码包含空格或非 ASCII 字符的查询参数值。", "解码百分号编码的路径片段或参数值。"],
    steps: ["编码时输入普通组件文本，解码时输入编码文本。", "选择方向。", "检查结果；错误的转义序列会提示无效。"],
    example: { title: "编码组件", description: "a b/世界 会变为 a%20b%2F%E4%B8%96%E7%95%8C，因为斜杠也被当作组件数据。" },
    principles: ["编码使用 JavaScript encodeURIComponent，解码使用 decodeURIComponent，并处理 UTF-8 百分号序列。"],
    limitations: ["不会解析或校验完整 URL，输入中的 /、?、&、= 等保留分隔符也会被编码。", "加号不会自动变为空格，HTML 表单编码规则不同。", "错误的百分号转义会被拒绝。"],
    faqs: [
      { question: "为什么斜杠也被编码？", answer: "因为 encodeURIComponent 把整段输入视为一个组件，斜杠不是路径分隔符。" },
      { question: "解码会校验完整网址吗？", answer: "不会，只处理输入文本中的百分号转义。" },
    ],
    aliases: ["百分号编码", "URL 编码", "URL 解码", "encodeURIComponent"],
    keywords: ["URL", "URI", "百分号编码", "组件", "decodeURIComponent"],
  }),
  uuid: localize("uuid", {
    summary: "使用浏览器加密随机源生成随机 UUID v4。",
    introduction: "UUID 生成器在当前浏览器创建版本 4 UUID，适合在不便使用中央顺序编号时生成标识符。",
    useCases: ["为测试数据或本地记录创建 ID。", "开发时生成请求或关联标识符。"],
    steps: ["打开工具获得初始 UUID。", "点击生成以替换为新的 UUID v4。", "复制标识符。"],
    example: { title: "UUID v4 结构", description: "生成值采用 8-4-4-4-12 十六进制布局，版本和变体位由浏览器设置。" },
    principles: ["实现调用 crypto.randomUUID()，由浏览器的加密安全随机源生成 UUID 版本 4。"],
    limitations: ["UUID 只是标识符，不是密码、访问令牌或记录存在证明。", "碰撞概率极低，但不是数学上的绝对唯一保证。"],
    faqs: [
      { question: "生成哪个版本？", answer: "只生成 UUID 版本 4。" },
      { question: "能从中读取生成时间吗？", answer: "不能，版本 4 是随机标识符，不编码时间。" },
    ],
    aliases: ["GUID 生成器", "UUID v4", "随机 ID", "唯一标识符"],
    keywords: ["UUID", "GUID", "版本 4", "随机", "标识符", "加密随机"],
  }),
  timestamp: localize("timestamp", {
    summary: "在 Unix 秒／毫秒、ISO UTC 文本和本地日期时间之间转换。",
    introduction: "数值输入需要明确选择秒或毫秒，并显示 ISO 8601 UTC 文本；datetime-local 输入会按浏览器本地时区转换为 Unix 秒和毫秒。",
    useCases: ["把 API 时间戳查看为可读 UTC 时间。", "为选定的本地日期时间生成秒和毫秒值。"],
    steps: ["输入整数时间戳并选择秒或毫秒，或选择本地日期时间。", "查看 ISO UTC 或秒／毫秒结果。", "用互换按钮在两个区域之间转移有效值。"],
    example: { title: "Unix 时间示例", description: "1704067200 秒会转换为 2024-01-01T00:00:00.000Z。" },
    principles: ["JavaScript Date 以 Unix 纪元后的毫秒表示时间；toISOString 输出 UTC，datetime-local 按浏览器本地时区解释。"],
    limitations: ["小数和超范围时间戳会被拒绝，单位不会再根据位数猜测。", "datetime-local 不含时区后缀，会使用字段旁显示的当前浏览器时区。", "JavaScript Date 不表示闰秒。"],
    faqs: [
      { question: "如何区分秒和毫秒？", answer: "由用户明确选择单位，不根据位数猜测历史或远期时间。" },
      { question: "ISO 结果为什么以 Z 结尾？", answer: "Z 表示 UTC，工具会把时刻转换为 UTC 文本。" },
      { question: "日期时间输入使用哪个时区？", answer: "使用浏览器当前本地时区。" },
    ],
    aliases: ["Unix 时间戳", "纪元转换", "秒转日期", "毫秒转日期"],
    keywords: ["时间戳", "Unix", "纪元", "ISO 8601", "UTC", "时区", "毫秒"],
  }),
  case: localize("case", {
    summary: "把文本转换为大写、小写、标题式或基础 camelCase。",
    introduction: "文本大小写转换使用浏览器的 Unicode 大小写操作和简单词形规则，适合本地处理标签、标题和标识符。",
    useCases: ["统一标题的大写或小写形式。", "把空格、下划线或连字符分隔的文本转为基础 camelCase。"],
    steps: ["输入或粘贴文本。", "选择 upper、lower、title 或 camel。", "检查并复制结果。"],
    example: { title: "基础驼峰", description: "Lite tools_example 会变成 liteToolsExample。" },
    principles: ["大写和小写使用浏览器本地化规则；标题模式处理 Unicode 单词；驼峰模式移除空格、下划线和连字符并大写后续字符。"],
    limitations: ["标题模式不理解各语言编辑规范中的小词例外。", "驼峰模式不会识别所有标点或缩写惯例。", "某些 Unicode 大小写转换会改变字符串长度。"],
    faqs: [
      { question: "标题模式是否遵循新闻标题规范？", answer: "不会，它只按规则大写词首。" },
      { question: "驼峰模式会保留缩写吗？", answer: "不一定，它没有缩写词典。" },
    ],
    aliases: ["大写转换", "小写转换", "标题格式", "驼峰格式"],
    keywords: ["文本大小写", "大写", "小写", "标题", "camelCase", "Unicode"],
  }),
  text: localize("text", {
    summary: "在本地统计用户可见的 Unicode 字素、空白分隔词组和文本行数。",
    introduction: "字数统计按当前实现的明确规则报告字符、字词和行数，适合快速检查文本，不等同于语言学或出版统计。",
    useCases: ["快速查看短稿长度。", "统计粘贴笔记或小段文本的行数。"],
    steps: ["输入或粘贴文本。", "查看实时字符、字词和行数。", "需要时复制三项统计摘要。"],
    example: { title: "中英混合文本", description: "one two 换行后输入 三，会得到 9 个字符、3 个空白分隔词组和 2 行。" },
    principles: ["环境支持时使用 Intl.Segmenter 的字素边界，因此组合字符和连接 Emoji 按一个可见字符统计；字词按空白分隔；行按 CRLF、CR 或 LF 分隔，空输入为 0 行。"],
    limitations: ["没有空格的中文句子会被统计为一个字词组，不会自动分词。", "旧浏览器的后备算法只近似处理常见组合字符与 Emoji，可能与完整 Unicode 字素分段不同。", "不统计页数、句子、阅读时间或字节数。"],
    faqs: [
      { question: "空格算字符吗？", answer: "算，字符统计包含空白字素。" },
      { question: "中文词数如何计算？", answer: "只按空白边界，连续无空格中文算一个词组。" },
      { question: "末尾换行会增加行数吗？", answer: "输入以换行结束时，分隔规则可能产生一个末尾空行。" },
    ],
    aliases: ["字符统计", "词数统计", "行数统计", "文本统计"],
    keywords: ["字数", "字符", "字词", "行数", "空白", "Unicode"],
  }),
  color: localize("color", {
    summary: "把 HEX 转为 RGB，或把 RGB 通道转换为 HEX 和 HSL。",
    introduction: "颜色转换支持三位或六位 HEX，以及红、绿、蓝数值通道，输出 CSS 风格的 RGB、HEX 和 HSL。",
    useCases: ["查看设计 HEX 颜色的 RGB 通道。", "从 RGB 数值生成 HEX 和 HSL 表示。"],
    steps: ["输入 HEX 或 0 至 255 的 RGB 通道。", "查看对应颜色格式。", "复制生成文本。"],
    example: { title: "绿色示例", description: "#187b69 转换为 rgb(24, 123, 105)，相同 RGB 会生成 #187b69 和 HSL。" },
    principles: ["HEX 用两位十六进制表示每个 RGB 通道；HSL 根据归一化 RGB 的最大最小值计算并取整。"],
    limitations: ["生成 HEX 时 RGB 会四舍五入为整数。", "不处理透明度、广色域、色彩配置、LAB 或 LCH。", "HSL 取整可能导致往返转换不完全一致。"],
    faqs: [
      { question: "支持三位 HEX 吗？", answer: "支持，例如 #abc 会扩展为 #aabbcc。" },
      { question: "RGB 超出范围会被截断吗？", answer: "不会，低于 0 或高于 255 会被判为无效。" },
    ],
    aliases: ["HEX 转 RGB", "RGB 转 HEX", "RGB 转 HSL", "CSS 颜色转换"],
    keywords: ["颜色", "HEX", "RGB", "HSL", "CSS", "调色板"],
  }),
  percentage: localize("percentage", {
    summary: "计算一个基准数值的指定百分比。",
    introduction: "百分比计算回答“V 的 P% 是多少”，直接执行乘法，接受有限的正数和负数。",
    useCases: ["计算税额或小费金额。", "求一个测量值的 12.5% 等比例数值。"],
    steps: ["输入百分比。", "输入基准数值。", "查看并复制结果。"],
    example: { title: "百分之十", description: "250 的 10% 是 25。" },
    principles: ["公式为：结果 = 百分比 ÷ 100 × 基准数值。"],
    limitations: ["不自动计算百分比变化、反向百分比、利润率或加总后的总数。", "允许负数和超过 100% 的值，因为一般算术中可能有意义。"],
    faqs: [
      { question: "结果包含原数值吗？", answer: "不包含，只返回百分比对应的数值。" },
      { question: "百分比可以超过 100 吗？", answer: "可以，当前实现接受任何有限百分比。" },
    ],
    aliases: ["数值百分比", "百分比工具", "求百分之几", "percent 计算"],
    keywords: ["百分比", "比例", "基准数值", "计算"],
  }),
  discount: localize("discount", {
    summary: "根据原价和折扣率计算折后价与节省金额。",
    introduction: "折扣计算对非负原价应用一次百分比折扣，同时显示折后价和节省金额。",
    useCases: ["购物前核对促销价格。", "比较某个折扣百分比可以节省多少。"],
    steps: ["输入原价。", "输入 0 至 100 的折扣率。", "查看折后价和节省金额。"],
    example: { title: "八五折", description: "原价 100、折扣率 15% 时，折后价为 85，节省 15。" },
    principles: ["折后价 = 原价 × (1 − 折扣率 ÷ 100)；节省 = 原价 × 折扣率 ÷ 100。"],
    limitations: ["不包含税费、运费、优惠券、阶梯折扣或汇率。", "结果只作数值参考，不是金融建议或商家报价。"],
    faqs: [
      { question: "折扣率可以超过 100% 吗？", answer: "不可以，低于 0 或高于 100 会被拒绝。" },
      { question: "工具知道货币吗？", answer: "不知道，输入和结果使用同一货币即可。" },
    ],
    aliases: ["折后价计算", "促销价格", "优惠计算", "节省金额"],
    keywords: ["折扣", "促销", "价格", "节省", "百分比"],
  }),
  bmi: localize("bmi", {
    summary: "用千克和厘米计算成人 BMI 一般参考值。",
    introduction: "BMI 计算把千克体重除以米制身高的平方。BMI 是群体筛查指标，不能直接测量身体成分，也不能诊断健康状况。",
    useCases: ["用公制数据计算成人 BMI 一般参考。", "核对与专业人员讨论的 BMI 算术过程。"],
    steps: ["输入体重（千克）。", "输入身高（厘米）。", "查看 BMI 数值和健康提示。"],
    example: { title: "公制 BMI", description: "体重 70 千克、身高 175 厘米时，BMI 约为 22.9。" },
    principles: ["BMI = 体重（kg）÷ 身高²（m²），实现会先把厘米除以 100 转为米。"],
    limitations: ["显示的成人范围是一般筛查标签，不构成医疗诊断。", "BMI 不区分肌肉、脂肪、骨骼、年龄、性别、族群、孕期或个体临床情况。", "儿童需要结合年龄和性别的生长参考，不能使用这些成人范围。"],
    faqs: [
      { question: "显示的 BMI 范围会构成诊断吗？", answer: "不会，这些只是成人一般筛查标签，不构成诊断。" },
      { question: "儿童能使用相同解释吗？", answer: "不能，儿童和青少年需要按年龄和性别评估。" },
      { question: "为什么要转换厘米？", answer: "BMI 公式使用米，所以先将厘米除以 100。" },
    ],
    aliases: ["身体质量指数", "BMI 查询", "千克厘米 BMI", "健康计算"],
    keywords: ["BMI", "身体质量指数", "体重", "身高", "健康", "非诊断"],
  }),
  compound: localize("compound", {
    summary: "按本金、年利率、年数和所选复利频率估算增长。",
    introduction: "复利计算按所选的每年复利次数估算本金增长，返回期末金额及其与本金的差额。",
    useCases: ["探索简化的储蓄增长情景。", "比较名义年利率经过若干年每月复利后的结果。"],
    steps: ["输入本金。", "输入年利率、年数和每年复利次数。", "查看估算金额和利息。"],
    example: { title: "每月复利", description: "本金 1,000、年利率 12%、1 年，每月复利后约为 1,126.83。" },
    principles: ["实现公式为 A = P(1 + r/n)^(nt)：年利率先除以 100，n 为所选的每年整数复利次数。"],
    limitations: ["界面允许每年 1 至 365 次复利，不包含追加投入、提取、费用、税款、通胀、变动利率或计息日规则。", "结果是数学估算，不构成金融建议或收益承诺。", "导致周期增长因子不大于零或结果非有限的输入会被拒绝。"],
    faqs: [
      { question: "可以选择按年、按月或按日复利吗？", answer: "可以，分别输入每年 1、12 或最多 365 次复利。" },
      { question: "包含定期投入吗？", answer: "不包含，只计算一次初始本金。" },
      { question: "显示利息是单利吗？", answer: "不是，是最终复利金额减去本金。" },
    ],
    aliases: ["复利计算", "每月复利", "投资增长", "利息计算"],
    keywords: ["复利", "本金", "年利率", "年数", "每月", "利息"],
  }),
  datecalc: localize("datecalc", {
    summary: "计算两个浏览器日期输入之间的绝对经过天数。",
    introduction: "日期间隔会严格校验两个 Gregorian 日历日期，再返回两者之间的绝对经过日历天数。",
    useCases: ["查看两个普通日期之间相隔多少天。", "无需手工数日历即可比较两个截止日。"],
    steps: ["选择开始日期。", "选择结束日期。", "查看绝对经过天数。"],
    example: { title: "一月间隔", description: "从 2024-01-01 到 2024-01-31 返回 30 天。" },
    principles: ["每个严格的 YYYY-MM-DD 输入都按 UTC Gregorian 日历日期构造，再计算绝对日期边界差，从而不受本地时区或夏令时影响。"],
    limitations: ["结果是经过差值，不同时包含首尾日期；1 月 1 日至 1 月 31 日为 30 天而不是 31 天。", "2 月 30 日等自动滚动日期会被拒绝。", "不计算工作日、节假日、月份或排期。"],
    faqs: [
      { question: "日期顺序有影响吗？", answer: "没有，工具使用绝对差值。" },
      { question: "是否同时包含开始和结束日？", answer: "不包含，结果是两者之间的经过间隔。" },
      { question: "会排除周末吗？", answer: "不会，所有经过日同等处理。" },
    ],
    aliases: ["日期相差天数", "日期差", "天数间隔", "经过天数"],
    keywords: ["日期", "间隔", "差值", "天数", "经过", "时区"],
  }),
  qr: localize("qr", {
    summary: "在本地把文本或 URL 生成为可自定义的 QR Code PNG。",
    introduction: "QR Code 生成器在浏览器编码输入内容，可设置图片尺寸、前景色和背景色，并下载 PNG；原始文本有独立复制操作。",
    useCases: ["为公开网址生成 QR Code。", "把短文本编码后在设备之间传递。"],
    steps: ["输入要编码的完整文本或 URL。", "选择 PNG 尺寸及高对比前景、背景颜色。", "用目标设备试扫预览，再下载 PNG。"],
    example: { title: "网址 QR Code", description: "输入 https://example.com 会生成包含该文本的 QR Code，并提供 PNG 下载。" },
    principles: ["浏览器端 qrcode 库选择符号并渲染 PNG data URL。内容越多，通常需要的模块越多；图片尺寸不变时单个模块会更小。"],
    limitations: ["界面拒绝空内容以及超过 1,200 个 UTF-8 字节的输入，作为保守可靠性限制；非 ASCII 字符可能占多个字节，实际容量还受 QR 编码模式影响。", "扫码兼容性受对比度、图片尺寸、静区、打印、摄像头和扫码软件影响，最终文件必须实测。", "QR Code 只是保存输入内容，不会验证网址安全性，也不会加密内容。"],
    faqs: [
      { question: "QR 内容会上传吗？", answer: "不会，图片在当前浏览器生成。" },
      { question: "长内容为什么难扫？", answer: "数据越多符号越密，在固定图片尺寸下模块更小。" },
      { question: "什么颜色最稳妥？", answer: "通常使用深色前景和浅色高对比背景。" },
    ],
    aliases: ["QR 生成器", "二维码生成", "文本转 QR", "网址 QR"],
    keywords: ["QR Code", "二维码", "PNG", "扫码", "容量", "对比度", "本地"],
  }),
};
